// Code generated by ent, DO NOT EDIT.

package useractivationjourney

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the useractivationjourney type in the database.
	Label = "user_activation_journey"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCampaignSource holds the string denoting the campaign_source field in the database.
	FieldCampaignSource = "campaign_source"
	// FieldStarterState holds the string denoting the starter_state field in the database.
	FieldStarterState = "starter_state"
	// FieldStarterSubscriptionID holds the string denoting the starter_subscription_id field in the database.
	FieldStarterSubscriptionID = "starter_subscription_id"
	// FieldStarterGrantedAt holds the string denoting the starter_granted_at field in the database.
	FieldStarterGrantedAt = "starter_granted_at"
	// FieldStarterExpiresAt holds the string denoting the starter_expires_at field in the database.
	FieldStarterExpiresAt = "starter_expires_at"
	// FieldRecallState holds the string denoting the recall_state field in the database.
	FieldRecallState = "recall_state"
	// FieldRecallSubscriptionID holds the string denoting the recall_subscription_id field in the database.
	FieldRecallSubscriptionID = "recall_subscription_id"
	// FieldRecallClaimedAt holds the string denoting the recall_claimed_at field in the database.
	FieldRecallClaimedAt = "recall_claimed_at"
	// FieldRecallExpiresAt holds the string denoting the recall_expires_at field in the database.
	FieldRecallExpiresAt = "recall_expires_at"
	// FieldFirstSuccessAt holds the string denoting the first_success_at field in the database.
	FieldFirstSuccessAt = "first_success_at"
	// FieldNoAttemptEmailSentAt holds the string denoting the no_attempt_email_sent_at field in the database.
	FieldNoAttemptEmailSentAt = "no_attempt_email_sent_at"
	// FieldAttemptedEmailSentAt holds the string denoting the attempted_email_sent_at field in the database.
	FieldAttemptedEmailSentAt = "attempted_email_sent_at"
	// FieldPaidSupportEmailSentAt holds the string denoting the paid_support_email_sent_at field in the database.
	FieldPaidSupportEmailSentAt = "paid_support_email_sent_at"
	// FieldRecallAvailableEmailSentAt holds the string denoting the recall_available_email_sent_at field in the database.
	FieldRecallAvailableEmailSentAt = "recall_available_email_sent_at"
	// FieldRecallExpiredEmailSentAt holds the string denoting the recall_expired_email_sent_at field in the database.
	FieldRecallExpiredEmailSentAt = "recall_expired_email_sent_at"
	// FieldLastEmailSentAt holds the string denoting the last_email_sent_at field in the database.
	FieldLastEmailSentAt = "last_email_sent_at"
	// FieldLastEvaluatedAt holds the string denoting the last_evaluated_at field in the database.
	FieldLastEvaluatedAt = "last_evaluated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeStarterSubscription holds the string denoting the starter_subscription edge name in mutations.
	EdgeStarterSubscription = "starter_subscription"
	// EdgeRecallSubscription holds the string denoting the recall_subscription edge name in mutations.
	EdgeRecallSubscription = "recall_subscription"
	// Table holds the table name of the useractivationjourney in the database.
	Table = "user_activation_journeys"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_activation_journeys"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// StarterSubscriptionTable is the table that holds the starter_subscription relation/edge.
	StarterSubscriptionTable = "user_activation_journeys"
	// StarterSubscriptionInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	StarterSubscriptionInverseTable = "user_subscriptions"
	// StarterSubscriptionColumn is the table column denoting the starter_subscription relation/edge.
	StarterSubscriptionColumn = "starter_subscription_id"
	// RecallSubscriptionTable is the table that holds the recall_subscription relation/edge.
	RecallSubscriptionTable = "user_activation_journeys"
	// RecallSubscriptionInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	RecallSubscriptionInverseTable = "user_subscriptions"
	// RecallSubscriptionColumn is the table column denoting the recall_subscription relation/edge.
	RecallSubscriptionColumn = "recall_subscription_id"
)

// Columns holds all SQL columns for useractivationjourney fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldCampaignSource,
	FieldStarterState,
	FieldStarterSubscriptionID,
	FieldStarterGrantedAt,
	FieldStarterExpiresAt,
	FieldRecallState,
	FieldRecallSubscriptionID,
	FieldRecallClaimedAt,
	FieldRecallExpiresAt,
	FieldFirstSuccessAt,
	FieldNoAttemptEmailSentAt,
	FieldAttemptedEmailSentAt,
	FieldPaidSupportEmailSentAt,
	FieldRecallAvailableEmailSentAt,
	FieldRecallExpiredEmailSentAt,
	FieldLastEmailSentAt,
	FieldLastEvaluatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultCampaignSource holds the default value on creation for the "campaign_source" field.
	DefaultCampaignSource string
	// CampaignSourceValidator is a validator for the "campaign_source" field. It is called by the builders before save.
	CampaignSourceValidator func(string) error
)

// StarterState defines the type for the "starter_state" enum field.
type StarterState string

// StarterStatePending is the default value of the StarterState enum.
const DefaultStarterState = StarterStatePending

// StarterState values.
const (
	StarterStatePending StarterState = "pending"
	StarterStateGranted StarterState = "granted"
	StarterStateExpired StarterState = "expired"
)

func (ss StarterState) String() string {
	return string(ss)
}

// StarterStateValidator is a validator for the "starter_state" field enum values. It is called by the builders before save.
func StarterStateValidator(ss StarterState) error {
	switch ss {
	case StarterStatePending, StarterStateGranted, StarterStateExpired:
		return nil
	default:
		return fmt.Errorf("useractivationjourney: invalid enum value for starter_state field: %q", ss)
	}
}

// RecallState defines the type for the "recall_state" enum field.
type RecallState string

// RecallStateLocked is the default value of the RecallState enum.
const DefaultRecallState = RecallStateLocked

// RecallState values.
const (
	RecallStateLocked        RecallState = "locked"
	RecallStateClaimable     RecallState = "claimable"
	RecallStateClaimed       RecallState = "claimed"
	RecallStateExpired       RecallState = "expired"
	RecallStateBlockedPaid   RecallState = "blocked_paid"
	RecallStateClosedSuccess RecallState = "closed_success"
)

func (rs RecallState) String() string {
	return string(rs)
}

// RecallStateValidator is a validator for the "recall_state" field enum values. It is called by the builders before save.
func RecallStateValidator(rs RecallState) error {
	switch rs {
	case RecallStateLocked, RecallStateClaimable, RecallStateClaimed, RecallStateExpired, RecallStateBlockedPaid, RecallStateClosedSuccess:
		return nil
	default:
		return fmt.Errorf("useractivationjourney: invalid enum value for recall_state field: %q", rs)
	}
}

// OrderOption defines the ordering options for the UserActivationJourney queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCampaignSource orders the results by the campaign_source field.
func ByCampaignSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignSource, opts...).ToFunc()
}

// ByStarterState orders the results by the starter_state field.
func ByStarterState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStarterState, opts...).ToFunc()
}

// ByStarterSubscriptionID orders the results by the starter_subscription_id field.
func ByStarterSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStarterSubscriptionID, opts...).ToFunc()
}

// ByStarterGrantedAt orders the results by the starter_granted_at field.
func ByStarterGrantedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStarterGrantedAt, opts...).ToFunc()
}

// ByStarterExpiresAt orders the results by the starter_expires_at field.
func ByStarterExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStarterExpiresAt, opts...).ToFunc()
}

// ByRecallState orders the results by the recall_state field.
func ByRecallState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecallState, opts...).ToFunc()
}

// ByRecallSubscriptionID orders the results by the recall_subscription_id field.
func ByRecallSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecallSubscriptionID, opts...).ToFunc()
}

// ByRecallClaimedAt orders the results by the recall_claimed_at field.
func ByRecallClaimedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecallClaimedAt, opts...).ToFunc()
}

// ByRecallExpiresAt orders the results by the recall_expires_at field.
func ByRecallExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecallExpiresAt, opts...).ToFunc()
}

// ByFirstSuccessAt orders the results by the first_success_at field.
func ByFirstSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSuccessAt, opts...).ToFunc()
}

// ByNoAttemptEmailSentAt orders the results by the no_attempt_email_sent_at field.
func ByNoAttemptEmailSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoAttemptEmailSentAt, opts...).ToFunc()
}

// ByAttemptedEmailSentAt orders the results by the attempted_email_sent_at field.
func ByAttemptedEmailSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptedEmailSentAt, opts...).ToFunc()
}

// ByPaidSupportEmailSentAt orders the results by the paid_support_email_sent_at field.
func ByPaidSupportEmailSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidSupportEmailSentAt, opts...).ToFunc()
}

// ByRecallAvailableEmailSentAt orders the results by the recall_available_email_sent_at field.
func ByRecallAvailableEmailSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecallAvailableEmailSentAt, opts...).ToFunc()
}

// ByRecallExpiredEmailSentAt orders the results by the recall_expired_email_sent_at field.
func ByRecallExpiredEmailSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecallExpiredEmailSentAt, opts...).ToFunc()
}

// ByLastEmailSentAt orders the results by the last_email_sent_at field.
func ByLastEmailSentAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEmailSentAt, opts...).ToFunc()
}

// ByLastEvaluatedAt orders the results by the last_evaluated_at field.
func ByLastEvaluatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastEvaluatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByStarterSubscriptionField orders the results by starter_subscription field.
func ByStarterSubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStarterSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByRecallSubscriptionField orders the results by recall_subscription field.
func ByRecallSubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecallSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
func newStarterSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StarterSubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, StarterSubscriptionTable, StarterSubscriptionColumn),
	)
}
func newRecallSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecallSubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RecallSubscriptionTable, RecallSubscriptionColumn),
	)
}
