// Code generated by ent, DO NOT EDIT.

package useractivationjourney

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldUserID, v))
}

// CampaignSource applies equality check predicate on the "campaign_source" field. It's identical to CampaignSourceEQ.
func CampaignSource(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldCampaignSource, v))
}

// StarterSubscriptionID applies equality check predicate on the "starter_subscription_id" field. It's identical to StarterSubscriptionIDEQ.
func StarterSubscriptionID(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldStarterSubscriptionID, v))
}

// StarterGrantedAt applies equality check predicate on the "starter_granted_at" field. It's identical to StarterGrantedAtEQ.
func StarterGrantedAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldStarterGrantedAt, v))
}

// StarterExpiresAt applies equality check predicate on the "starter_expires_at" field. It's identical to StarterExpiresAtEQ.
func StarterExpiresAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldStarterExpiresAt, v))
}

// RecallSubscriptionID applies equality check predicate on the "recall_subscription_id" field. It's identical to RecallSubscriptionIDEQ.
func RecallSubscriptionID(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallSubscriptionID, v))
}

// RecallClaimedAt applies equality check predicate on the "recall_claimed_at" field. It's identical to RecallClaimedAtEQ.
func RecallClaimedAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallClaimedAt, v))
}

// RecallExpiresAt applies equality check predicate on the "recall_expires_at" field. It's identical to RecallExpiresAtEQ.
func RecallExpiresAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallExpiresAt, v))
}

// FirstSuccessAt applies equality check predicate on the "first_success_at" field. It's identical to FirstSuccessAtEQ.
func FirstSuccessAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldFirstSuccessAt, v))
}

// NoAttemptEmailSentAt applies equality check predicate on the "no_attempt_email_sent_at" field. It's identical to NoAttemptEmailSentAtEQ.
func NoAttemptEmailSentAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldNoAttemptEmailSentAt, v))
}

// AttemptedEmailSentAt applies equality check predicate on the "attempted_email_sent_at" field. It's identical to AttemptedEmailSentAtEQ.
func AttemptedEmailSentAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldAttemptedEmailSentAt, v))
}

// PaidSupportEmailSentAt applies equality check predicate on the "paid_support_email_sent_at" field. It's identical to PaidSupportEmailSentAtEQ.
func PaidSupportEmailSentAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldPaidSupportEmailSentAt, v))
}

// RecallAvailableEmailSentAt applies equality check predicate on the "recall_available_email_sent_at" field. It's identical to RecallAvailableEmailSentAtEQ.
func RecallAvailableEmailSentAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallAvailableEmailSentAt, v))
}

// RecallExpiredEmailSentAt applies equality check predicate on the "recall_expired_email_sent_at" field. It's identical to RecallExpiredEmailSentAtEQ.
func RecallExpiredEmailSentAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallExpiredEmailSentAt, v))
}

// LastEmailSentAt applies equality check predicate on the "last_email_sent_at" field. It's identical to LastEmailSentAtEQ.
func LastEmailSentAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldLastEmailSentAt, v))
}

// LastEvaluatedAt applies equality check predicate on the "last_evaluated_at" field. It's identical to LastEvaluatedAtEQ.
func LastEvaluatedAt(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldLastEvaluatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldUserID, vs...))
}

// CampaignSourceEQ applies the EQ predicate on the "campaign_source" field.
func CampaignSourceEQ(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldCampaignSource, v))
}

// CampaignSourceNEQ applies the NEQ predicate on the "campaign_source" field.
func CampaignSourceNEQ(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldCampaignSource, v))
}

// CampaignSourceIn applies the In predicate on the "campaign_source" field.
func CampaignSourceIn(vs ...string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldCampaignSource, vs...))
}

// CampaignSourceNotIn applies the NotIn predicate on the "campaign_source" field.
func CampaignSourceNotIn(vs ...string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldCampaignSource, vs...))
}

// CampaignSourceGT applies the GT predicate on the "campaign_source" field.
func CampaignSourceGT(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldCampaignSource, v))
}

// CampaignSourceGTE applies the GTE predicate on the "campaign_source" field.
func CampaignSourceGTE(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldCampaignSource, v))
}

// CampaignSourceLT applies the LT predicate on the "campaign_source" field.
func CampaignSourceLT(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldCampaignSource, v))
}

// CampaignSourceLTE applies the LTE predicate on the "campaign_source" field.
func CampaignSourceLTE(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldCampaignSource, v))
}

// CampaignSourceContains applies the Contains predicate on the "campaign_source" field.
func CampaignSourceContains(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldContains(FieldCampaignSource, v))
}

// CampaignSourceHasPrefix applies the HasPrefix predicate on the "campaign_source" field.
func CampaignSourceHasPrefix(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldHasPrefix(FieldCampaignSource, v))
}

// CampaignSourceHasSuffix applies the HasSuffix predicate on the "campaign_source" field.
func CampaignSourceHasSuffix(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldHasSuffix(FieldCampaignSource, v))
}

// CampaignSourceEqualFold applies the EqualFold predicate on the "campaign_source" field.
func CampaignSourceEqualFold(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEqualFold(FieldCampaignSource, v))
}

// CampaignSourceContainsFold applies the ContainsFold predicate on the "campaign_source" field.
func CampaignSourceContainsFold(v string) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldContainsFold(FieldCampaignSource, v))
}

// StarterStateEQ applies the EQ predicate on the "starter_state" field.
func StarterStateEQ(v StarterState) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldStarterState, v))
}

// StarterStateNEQ applies the NEQ predicate on the "starter_state" field.
func StarterStateNEQ(v StarterState) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldStarterState, v))
}

// StarterStateIn applies the In predicate on the "starter_state" field.
func StarterStateIn(vs ...StarterState) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldStarterState, vs...))
}

// StarterStateNotIn applies the NotIn predicate on the "starter_state" field.
func StarterStateNotIn(vs ...StarterState) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldStarterState, vs...))
}

// StarterSubscriptionIDEQ applies the EQ predicate on the "starter_subscription_id" field.
func StarterSubscriptionIDEQ(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldStarterSubscriptionID, v))
}

// StarterSubscriptionIDNEQ applies the NEQ predicate on the "starter_subscription_id" field.
func StarterSubscriptionIDNEQ(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldStarterSubscriptionID, v))
}

// StarterSubscriptionIDIn applies the In predicate on the "starter_subscription_id" field.
func StarterSubscriptionIDIn(vs ...int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldStarterSubscriptionID, vs...))
}

// StarterSubscriptionIDNotIn applies the NotIn predicate on the "starter_subscription_id" field.
func StarterSubscriptionIDNotIn(vs ...int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldStarterSubscriptionID, vs...))
}

// StarterSubscriptionIDIsNil applies the IsNil predicate on the "starter_subscription_id" field.
func StarterSubscriptionIDIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldStarterSubscriptionID))
}

// StarterSubscriptionIDNotNil applies the NotNil predicate on the "starter_subscription_id" field.
func StarterSubscriptionIDNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldStarterSubscriptionID))
}

// StarterGrantedAtEQ applies the EQ predicate on the "starter_granted_at" field.
func StarterGrantedAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldStarterGrantedAt, v))
}

// StarterGrantedAtNEQ applies the NEQ predicate on the "starter_granted_at" field.
func StarterGrantedAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldStarterGrantedAt, v))
}

// StarterGrantedAtIn applies the In predicate on the "starter_granted_at" field.
func StarterGrantedAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldStarterGrantedAt, vs...))
}

// StarterGrantedAtNotIn applies the NotIn predicate on the "starter_granted_at" field.
func StarterGrantedAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldStarterGrantedAt, vs...))
}

// StarterGrantedAtGT applies the GT predicate on the "starter_granted_at" field.
func StarterGrantedAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldStarterGrantedAt, v))
}

// StarterGrantedAtGTE applies the GTE predicate on the "starter_granted_at" field.
func StarterGrantedAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldStarterGrantedAt, v))
}

// StarterGrantedAtLT applies the LT predicate on the "starter_granted_at" field.
func StarterGrantedAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldStarterGrantedAt, v))
}

// StarterGrantedAtLTE applies the LTE predicate on the "starter_granted_at" field.
func StarterGrantedAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldStarterGrantedAt, v))
}

// StarterGrantedAtIsNil applies the IsNil predicate on the "starter_granted_at" field.
func StarterGrantedAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldStarterGrantedAt))
}

// StarterGrantedAtNotNil applies the NotNil predicate on the "starter_granted_at" field.
func StarterGrantedAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldStarterGrantedAt))
}

// StarterExpiresAtEQ applies the EQ predicate on the "starter_expires_at" field.
func StarterExpiresAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldStarterExpiresAt, v))
}

// StarterExpiresAtNEQ applies the NEQ predicate on the "starter_expires_at" field.
func StarterExpiresAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldStarterExpiresAt, v))
}

// StarterExpiresAtIn applies the In predicate on the "starter_expires_at" field.
func StarterExpiresAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldStarterExpiresAt, vs...))
}

// StarterExpiresAtNotIn applies the NotIn predicate on the "starter_expires_at" field.
func StarterExpiresAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldStarterExpiresAt, vs...))
}

// StarterExpiresAtGT applies the GT predicate on the "starter_expires_at" field.
func StarterExpiresAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldStarterExpiresAt, v))
}

// StarterExpiresAtGTE applies the GTE predicate on the "starter_expires_at" field.
func StarterExpiresAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldStarterExpiresAt, v))
}

// StarterExpiresAtLT applies the LT predicate on the "starter_expires_at" field.
func StarterExpiresAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldStarterExpiresAt, v))
}

// StarterExpiresAtLTE applies the LTE predicate on the "starter_expires_at" field.
func StarterExpiresAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldStarterExpiresAt, v))
}

// StarterExpiresAtIsNil applies the IsNil predicate on the "starter_expires_at" field.
func StarterExpiresAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldStarterExpiresAt))
}

// StarterExpiresAtNotNil applies the NotNil predicate on the "starter_expires_at" field.
func StarterExpiresAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldStarterExpiresAt))
}

// RecallStateEQ applies the EQ predicate on the "recall_state" field.
func RecallStateEQ(v RecallState) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallState, v))
}

// RecallStateNEQ applies the NEQ predicate on the "recall_state" field.
func RecallStateNEQ(v RecallState) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldRecallState, v))
}

// RecallStateIn applies the In predicate on the "recall_state" field.
func RecallStateIn(vs ...RecallState) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldRecallState, vs...))
}

// RecallStateNotIn applies the NotIn predicate on the "recall_state" field.
func RecallStateNotIn(vs ...RecallState) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldRecallState, vs...))
}

// RecallSubscriptionIDEQ applies the EQ predicate on the "recall_subscription_id" field.
func RecallSubscriptionIDEQ(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallSubscriptionID, v))
}

// RecallSubscriptionIDNEQ applies the NEQ predicate on the "recall_subscription_id" field.
func RecallSubscriptionIDNEQ(v int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldRecallSubscriptionID, v))
}

// RecallSubscriptionIDIn applies the In predicate on the "recall_subscription_id" field.
func RecallSubscriptionIDIn(vs ...int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldRecallSubscriptionID, vs...))
}

// RecallSubscriptionIDNotIn applies the NotIn predicate on the "recall_subscription_id" field.
func RecallSubscriptionIDNotIn(vs ...int64) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldRecallSubscriptionID, vs...))
}

// RecallSubscriptionIDIsNil applies the IsNil predicate on the "recall_subscription_id" field.
func RecallSubscriptionIDIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldRecallSubscriptionID))
}

// RecallSubscriptionIDNotNil applies the NotNil predicate on the "recall_subscription_id" field.
func RecallSubscriptionIDNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldRecallSubscriptionID))
}

// RecallClaimedAtEQ applies the EQ predicate on the "recall_claimed_at" field.
func RecallClaimedAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallClaimedAt, v))
}

// RecallClaimedAtNEQ applies the NEQ predicate on the "recall_claimed_at" field.
func RecallClaimedAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldRecallClaimedAt, v))
}

// RecallClaimedAtIn applies the In predicate on the "recall_claimed_at" field.
func RecallClaimedAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldRecallClaimedAt, vs...))
}

// RecallClaimedAtNotIn applies the NotIn predicate on the "recall_claimed_at" field.
func RecallClaimedAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldRecallClaimedAt, vs...))
}

// RecallClaimedAtGT applies the GT predicate on the "recall_claimed_at" field.
func RecallClaimedAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldRecallClaimedAt, v))
}

// RecallClaimedAtGTE applies the GTE predicate on the "recall_claimed_at" field.
func RecallClaimedAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldRecallClaimedAt, v))
}

// RecallClaimedAtLT applies the LT predicate on the "recall_claimed_at" field.
func RecallClaimedAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldRecallClaimedAt, v))
}

// RecallClaimedAtLTE applies the LTE predicate on the "recall_claimed_at" field.
func RecallClaimedAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldRecallClaimedAt, v))
}

// RecallClaimedAtIsNil applies the IsNil predicate on the "recall_claimed_at" field.
func RecallClaimedAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldRecallClaimedAt))
}

// RecallClaimedAtNotNil applies the NotNil predicate on the "recall_claimed_at" field.
func RecallClaimedAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldRecallClaimedAt))
}

// RecallExpiresAtEQ applies the EQ predicate on the "recall_expires_at" field.
func RecallExpiresAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallExpiresAt, v))
}

// RecallExpiresAtNEQ applies the NEQ predicate on the "recall_expires_at" field.
func RecallExpiresAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldRecallExpiresAt, v))
}

// RecallExpiresAtIn applies the In predicate on the "recall_expires_at" field.
func RecallExpiresAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldRecallExpiresAt, vs...))
}

// RecallExpiresAtNotIn applies the NotIn predicate on the "recall_expires_at" field.
func RecallExpiresAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldRecallExpiresAt, vs...))
}

// RecallExpiresAtGT applies the GT predicate on the "recall_expires_at" field.
func RecallExpiresAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldRecallExpiresAt, v))
}

// RecallExpiresAtGTE applies the GTE predicate on the "recall_expires_at" field.
func RecallExpiresAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldRecallExpiresAt, v))
}

// RecallExpiresAtLT applies the LT predicate on the "recall_expires_at" field.
func RecallExpiresAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldRecallExpiresAt, v))
}

// RecallExpiresAtLTE applies the LTE predicate on the "recall_expires_at" field.
func RecallExpiresAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldRecallExpiresAt, v))
}

// RecallExpiresAtIsNil applies the IsNil predicate on the "recall_expires_at" field.
func RecallExpiresAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldRecallExpiresAt))
}

// RecallExpiresAtNotNil applies the NotNil predicate on the "recall_expires_at" field.
func RecallExpiresAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldRecallExpiresAt))
}

// FirstSuccessAtEQ applies the EQ predicate on the "first_success_at" field.
func FirstSuccessAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldFirstSuccessAt, v))
}

// FirstSuccessAtNEQ applies the NEQ predicate on the "first_success_at" field.
func FirstSuccessAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldFirstSuccessAt, v))
}

// FirstSuccessAtIn applies the In predicate on the "first_success_at" field.
func FirstSuccessAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldFirstSuccessAt, vs...))
}

// FirstSuccessAtNotIn applies the NotIn predicate on the "first_success_at" field.
func FirstSuccessAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldFirstSuccessAt, vs...))
}

// FirstSuccessAtGT applies the GT predicate on the "first_success_at" field.
func FirstSuccessAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldFirstSuccessAt, v))
}

// FirstSuccessAtGTE applies the GTE predicate on the "first_success_at" field.
func FirstSuccessAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldFirstSuccessAt, v))
}

// FirstSuccessAtLT applies the LT predicate on the "first_success_at" field.
func FirstSuccessAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldFirstSuccessAt, v))
}

// FirstSuccessAtLTE applies the LTE predicate on the "first_success_at" field.
func FirstSuccessAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldFirstSuccessAt, v))
}

// FirstSuccessAtIsNil applies the IsNil predicate on the "first_success_at" field.
func FirstSuccessAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldFirstSuccessAt))
}

// FirstSuccessAtNotNil applies the NotNil predicate on the "first_success_at" field.
func FirstSuccessAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldFirstSuccessAt))
}

// NoAttemptEmailSentAtEQ applies the EQ predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldNoAttemptEmailSentAt, v))
}

// NoAttemptEmailSentAtNEQ applies the NEQ predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldNoAttemptEmailSentAt, v))
}

// NoAttemptEmailSentAtIn applies the In predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldNoAttemptEmailSentAt, vs...))
}

// NoAttemptEmailSentAtNotIn applies the NotIn predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldNoAttemptEmailSentAt, vs...))
}

// NoAttemptEmailSentAtGT applies the GT predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldNoAttemptEmailSentAt, v))
}

// NoAttemptEmailSentAtGTE applies the GTE predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldNoAttemptEmailSentAt, v))
}

// NoAttemptEmailSentAtLT applies the LT predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldNoAttemptEmailSentAt, v))
}

// NoAttemptEmailSentAtLTE applies the LTE predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldNoAttemptEmailSentAt, v))
}

// NoAttemptEmailSentAtIsNil applies the IsNil predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldNoAttemptEmailSentAt))
}

// NoAttemptEmailSentAtNotNil applies the NotNil predicate on the "no_attempt_email_sent_at" field.
func NoAttemptEmailSentAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldNoAttemptEmailSentAt))
}

// AttemptedEmailSentAtEQ applies the EQ predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldAttemptedEmailSentAt, v))
}

// AttemptedEmailSentAtNEQ applies the NEQ predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldAttemptedEmailSentAt, v))
}

// AttemptedEmailSentAtIn applies the In predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldAttemptedEmailSentAt, vs...))
}

// AttemptedEmailSentAtNotIn applies the NotIn predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldAttemptedEmailSentAt, vs...))
}

// AttemptedEmailSentAtGT applies the GT predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldAttemptedEmailSentAt, v))
}

// AttemptedEmailSentAtGTE applies the GTE predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldAttemptedEmailSentAt, v))
}

// AttemptedEmailSentAtLT applies the LT predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldAttemptedEmailSentAt, v))
}

// AttemptedEmailSentAtLTE applies the LTE predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldAttemptedEmailSentAt, v))
}

// AttemptedEmailSentAtIsNil applies the IsNil predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldAttemptedEmailSentAt))
}

// AttemptedEmailSentAtNotNil applies the NotNil predicate on the "attempted_email_sent_at" field.
func AttemptedEmailSentAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldAttemptedEmailSentAt))
}

// PaidSupportEmailSentAtEQ applies the EQ predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldPaidSupportEmailSentAt, v))
}

// PaidSupportEmailSentAtNEQ applies the NEQ predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldPaidSupportEmailSentAt, v))
}

// PaidSupportEmailSentAtIn applies the In predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldPaidSupportEmailSentAt, vs...))
}

// PaidSupportEmailSentAtNotIn applies the NotIn predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldPaidSupportEmailSentAt, vs...))
}

// PaidSupportEmailSentAtGT applies the GT predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldPaidSupportEmailSentAt, v))
}

// PaidSupportEmailSentAtGTE applies the GTE predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldPaidSupportEmailSentAt, v))
}

// PaidSupportEmailSentAtLT applies the LT predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldPaidSupportEmailSentAt, v))
}

// PaidSupportEmailSentAtLTE applies the LTE predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldPaidSupportEmailSentAt, v))
}

// PaidSupportEmailSentAtIsNil applies the IsNil predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldPaidSupportEmailSentAt))
}

// PaidSupportEmailSentAtNotNil applies the NotNil predicate on the "paid_support_email_sent_at" field.
func PaidSupportEmailSentAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldPaidSupportEmailSentAt))
}

// RecallAvailableEmailSentAtEQ applies the EQ predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallAvailableEmailSentAt, v))
}

// RecallAvailableEmailSentAtNEQ applies the NEQ predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldRecallAvailableEmailSentAt, v))
}

// RecallAvailableEmailSentAtIn applies the In predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldRecallAvailableEmailSentAt, vs...))
}

// RecallAvailableEmailSentAtNotIn applies the NotIn predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldRecallAvailableEmailSentAt, vs...))
}

// RecallAvailableEmailSentAtGT applies the GT predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldRecallAvailableEmailSentAt, v))
}

// RecallAvailableEmailSentAtGTE applies the GTE predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldRecallAvailableEmailSentAt, v))
}

// RecallAvailableEmailSentAtLT applies the LT predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldRecallAvailableEmailSentAt, v))
}

// RecallAvailableEmailSentAtLTE applies the LTE predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldRecallAvailableEmailSentAt, v))
}

// RecallAvailableEmailSentAtIsNil applies the IsNil predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldRecallAvailableEmailSentAt))
}

// RecallAvailableEmailSentAtNotNil applies the NotNil predicate on the "recall_available_email_sent_at" field.
func RecallAvailableEmailSentAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldRecallAvailableEmailSentAt))
}

// RecallExpiredEmailSentAtEQ applies the EQ predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldRecallExpiredEmailSentAt, v))
}

// RecallExpiredEmailSentAtNEQ applies the NEQ predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldRecallExpiredEmailSentAt, v))
}

// RecallExpiredEmailSentAtIn applies the In predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldRecallExpiredEmailSentAt, vs...))
}

// RecallExpiredEmailSentAtNotIn applies the NotIn predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldRecallExpiredEmailSentAt, vs...))
}

// RecallExpiredEmailSentAtGT applies the GT predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldRecallExpiredEmailSentAt, v))
}

// RecallExpiredEmailSentAtGTE applies the GTE predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldRecallExpiredEmailSentAt, v))
}

// RecallExpiredEmailSentAtLT applies the LT predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldRecallExpiredEmailSentAt, v))
}

// RecallExpiredEmailSentAtLTE applies the LTE predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldRecallExpiredEmailSentAt, v))
}

// RecallExpiredEmailSentAtIsNil applies the IsNil predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldRecallExpiredEmailSentAt))
}

// RecallExpiredEmailSentAtNotNil applies the NotNil predicate on the "recall_expired_email_sent_at" field.
func RecallExpiredEmailSentAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldRecallExpiredEmailSentAt))
}

// LastEmailSentAtEQ applies the EQ predicate on the "last_email_sent_at" field.
func LastEmailSentAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldLastEmailSentAt, v))
}

// LastEmailSentAtNEQ applies the NEQ predicate on the "last_email_sent_at" field.
func LastEmailSentAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldLastEmailSentAt, v))
}

// LastEmailSentAtIn applies the In predicate on the "last_email_sent_at" field.
func LastEmailSentAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldLastEmailSentAt, vs...))
}

// LastEmailSentAtNotIn applies the NotIn predicate on the "last_email_sent_at" field.
func LastEmailSentAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldLastEmailSentAt, vs...))
}

// LastEmailSentAtGT applies the GT predicate on the "last_email_sent_at" field.
func LastEmailSentAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldLastEmailSentAt, v))
}

// LastEmailSentAtGTE applies the GTE predicate on the "last_email_sent_at" field.
func LastEmailSentAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldLastEmailSentAt, v))
}

// LastEmailSentAtLT applies the LT predicate on the "last_email_sent_at" field.
func LastEmailSentAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldLastEmailSentAt, v))
}

// LastEmailSentAtLTE applies the LTE predicate on the "last_email_sent_at" field.
func LastEmailSentAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldLastEmailSentAt, v))
}

// LastEmailSentAtIsNil applies the IsNil predicate on the "last_email_sent_at" field.
func LastEmailSentAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldLastEmailSentAt))
}

// LastEmailSentAtNotNil applies the NotNil predicate on the "last_email_sent_at" field.
func LastEmailSentAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldLastEmailSentAt))
}

// LastEvaluatedAtEQ applies the EQ predicate on the "last_evaluated_at" field.
func LastEvaluatedAtEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldEQ(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtNEQ applies the NEQ predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNEQ(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNEQ(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtIn applies the In predicate on the "last_evaluated_at" field.
func LastEvaluatedAtIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIn(FieldLastEvaluatedAt, vs...))
}

// LastEvaluatedAtNotIn applies the NotIn predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNotIn(vs ...time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotIn(FieldLastEvaluatedAt, vs...))
}

// LastEvaluatedAtGT applies the GT predicate on the "last_evaluated_at" field.
func LastEvaluatedAtGT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGT(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtGTE applies the GTE predicate on the "last_evaluated_at" field.
func LastEvaluatedAtGTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldGTE(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtLT applies the LT predicate on the "last_evaluated_at" field.
func LastEvaluatedAtLT(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLT(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtLTE applies the LTE predicate on the "last_evaluated_at" field.
func LastEvaluatedAtLTE(v time.Time) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldLTE(FieldLastEvaluatedAt, v))
}

// LastEvaluatedAtIsNil applies the IsNil predicate on the "last_evaluated_at" field.
func LastEvaluatedAtIsNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldIsNull(FieldLastEvaluatedAt))
}

// LastEvaluatedAtNotNil applies the NotNil predicate on the "last_evaluated_at" field.
func LastEvaluatedAtNotNil() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.FieldNotNull(FieldLastEvaluatedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStarterSubscription applies the HasEdge predicate on the "starter_subscription" edge.
func HasStarterSubscription() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, StarterSubscriptionTable, StarterSubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStarterSubscriptionWith applies the HasEdge predicate on the "starter_subscription" edge with a given conditions (other predicates).
func HasStarterSubscriptionWith(preds ...predicate.UserSubscription) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(func(s *sql.Selector) {
		step := newStarterSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRecallSubscription applies the HasEdge predicate on the "recall_subscription" edge.
func HasRecallSubscription() predicate.UserActivationJourney {
	return predicate.UserActivationJourney(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RecallSubscriptionTable, RecallSubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRecallSubscriptionWith applies the HasEdge predicate on the "recall_subscription" edge with a given conditions (other predicates).
func HasRecallSubscriptionWith(preds ...predicate.UserSubscription) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(func(s *sql.Selector) {
		step := newRecallSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserActivationJourney) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserActivationJourney) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserActivationJourney) predicate.UserActivationJourney {
	return predicate.UserActivationJourney(sql.NotPredicates(p))
}
