-- Persist exact upstream request/response attempts in physically reclaimable
-- Asia/Shanghai daily partitions. Payload bytes are zstd-compressed by the app.

CREATE TABLE IF NOT EXISTS public.upstream_audit_logs (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id                VARCHAR(64) NOT NULL DEFAULT '',
    attempt_no                INTEGER NOT NULL DEFAULT 1,
    user_id                   BIGINT NOT NULL DEFAULT 0,
    api_key_id                BIGINT NOT NULL DEFAULT 0,
    group_id                  BIGINT,
    account_id                BIGINT NOT NULL DEFAULT 0,
    endpoint                  VARCHAR(128) NOT NULL DEFAULT '',
    protocol                  VARCHAR(64) NOT NULL DEFAULT '',
    model                     VARCHAR(100) NOT NULL DEFAULT '',
    transport                 VARCHAR(16) NOT NULL DEFAULT '',
    method                    VARCHAR(16) NOT NULL DEFAULT '',
    upstream_url              TEXT NOT NULL DEFAULT '',
    request_headers_json      TEXT NOT NULL DEFAULT '{}',
    request_content_type      VARCHAR(128) NOT NULL DEFAULT '',
    request_sha256 VARCHAR(64) NOT NULL DEFAULT '',
    request_bytes             BIGINT NOT NULL DEFAULT 0,
    request_compressed_bytes  INTEGER NOT NULL DEFAULT 0,
    request_body_zstd BYTEA,
    response_status           INTEGER NOT NULL DEFAULT 0,
    response_headers_json     TEXT NOT NULL DEFAULT '{}',
    response_content_type     VARCHAR(128) NOT NULL DEFAULT '',
    response_sha256 VARCHAR(64) NOT NULL DEFAULT '',
    response_bytes            BIGINT NOT NULL DEFAULT 0,
    response_compressed_bytes INTEGER NOT NULL DEFAULT 0,
    response_body_zstd BYTEA,
    response_complete BOOLEAN NOT NULL DEFAULT FALSE,
    outcome                   VARCHAR(32) NOT NULL DEFAULT '',
    error_message             TEXT NOT NULL DEFAULT '',
    started_at                TIMESTAMPTZ NOT NULL,
    completed_at              TIMESTAMPTZ NOT NULL,
    created_at                TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (created_at, id),
    CONSTRAINT upstream_audit_attempt_no_positive CHECK (attempt_no >= 1),
    CONSTRAINT upstream_audit_request_sizes_valid CHECK (request_bytes >= 0 AND request_compressed_bytes >= 0),
    CONSTRAINT upstream_audit_response_sizes_valid CHECK (response_bytes >= 0 AND response_compressed_bytes >= 0),
    CONSTRAINT upstream_audit_response_status_valid CHECK (response_status BETWEEN 0 AND 599),
    CONSTRAINT upstream_audit_outcome_valid CHECK (outcome IN ('completed', 'transport_error', 'read_error', 'closed', 'capture_overflow', 'upstream_error', 'audit_error'))
) PARTITION BY RANGE (created_at);

CREATE INDEX IF NOT EXISTS idx_upstream_audit_request_attempt
    ON public.upstream_audit_logs(request_id, attempt_no, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_upstream_audit_user_created_at
    ON public.upstream_audit_logs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_upstream_audit_api_key_created_at
    ON public.upstream_audit_logs(api_key_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_upstream_audit_outcome_created_at
    ON public.upstream_audit_logs(outcome, created_at DESC);

CREATE OR REPLACE FUNCTION public.ensure_upstream_audit_partition(target_time TIMESTAMPTZ)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    local_day DATE := (target_time AT TIME ZONE 'Asia/Shanghai')::DATE;
    partition_name TEXT := 'upstream_audit_logs_' || to_char(local_day, 'YYYYMMDD');
    lower_bound TIMESTAMPTZ := local_day::TIMESTAMP AT TIME ZONE 'Asia/Shanghai';
    upper_bound TIMESTAMPTZ := (local_day + 1)::TIMESTAMP AT TIME ZONE 'Asia/Shanghai';
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended(partition_name, 0));
    IF local_day < (NOW() AT TIME ZONE 'Asia/Shanghai')::DATE
       AND to_regclass(format('public.%I', partition_name)) IS NULL THEN
        RAISE EXCEPTION 'refusing to recreate closed upstream audit partition %', partition_name;
    END IF;
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.upstream_audit_logs FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        lower_bound,
        upper_bound
    );
    RETURN partition_name;
END;
$$;

SELECT public.ensure_upstream_audit_partition(NOW());
SELECT public.ensure_upstream_audit_partition(NOW() + INTERVAL '1 day');
