// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeygroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// ApiKeyGroup is the model entity for the ApiKeyGroup schema.
type ApiKeyGroup struct {
	config `json:"-"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApiKeyGroupQuery when eager-loading is set.
	Edges        ApiKeyGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ApiKeyGroupEdges holds the relations/edges for other nodes in the graph.
type ApiKeyGroupEdges struct {
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApiKeyGroupEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApiKeyGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApiKeyGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeygroup.FieldAPIKeyID, apikeygroup.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case apikeygroup.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApiKeyGroup fields.
func (_m *ApiKeyGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeygroup.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case apikeygroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case apikeygroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApiKeyGroup.
// This includes values selected through modifiers, order, etc.
func (_m *ApiKeyGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKey queries the "api_key" edge of the ApiKeyGroup entity.
func (_m *ApiKeyGroup) QueryAPIKey() *APIKeyQuery {
	return NewApiKeyGroupClient(_m.config).QueryAPIKey(_m)
}

// QueryGroup queries the "group" edge of the ApiKeyGroup entity.
func (_m *ApiKeyGroup) QueryGroup() *GroupQuery {
	return NewApiKeyGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this ApiKeyGroup.
// Note that you need to call ApiKeyGroup.Unwrap() before calling this method if this ApiKeyGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ApiKeyGroup) Update() *ApiKeyGroupUpdateOne {
	return NewApiKeyGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ApiKeyGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ApiKeyGroup) Unwrap() *ApiKeyGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApiKeyGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ApiKeyGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ApiKeyGroup(")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ApiKeyGroups is a parsable slice of ApiKeyGroup.
type ApiKeyGroups []*ApiKeyGroup
