// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeygroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ApiKeyGroupUpdate is the builder for updating ApiKeyGroup entities.
type ApiKeyGroupUpdate struct {
	config
	hooks    []Hook
	mutation *ApiKeyGroupMutation
}

// Where appends a list predicates to the ApiKeyGroupUpdate builder.
func (_u *ApiKeyGroupUpdate) Where(ps ...predicate.ApiKeyGroup) *ApiKeyGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ApiKeyGroupUpdate) SetAPIKeyID(v int64) *ApiKeyGroupUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ApiKeyGroupUpdate) SetNillableAPIKeyID(v *int64) *ApiKeyGroupUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ApiKeyGroupUpdate) SetGroupID(v int64) *ApiKeyGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ApiKeyGroupUpdate) SetNillableGroupID(v *int64) *ApiKeyGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *ApiKeyGroupUpdate) SetAPIKey(v *APIKey) *ApiKeyGroupUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ApiKeyGroupUpdate) SetGroup(v *Group) *ApiKeyGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the ApiKeyGroupMutation object of the builder.
func (_u *ApiKeyGroupUpdate) Mutation() *ApiKeyGroupMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *ApiKeyGroupUpdate) ClearAPIKey() *ApiKeyGroupUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ApiKeyGroupUpdate) ClearGroup() *ApiKeyGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiKeyGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiKeyGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiKeyGroupUpdate) check() error {
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKeyGroup.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKeyGroup.group"`)
	}
	return nil
}

func (_u *ApiKeyGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeygroup.Table, apikeygroup.Columns, sqlgraph.NewFieldSpec(apikeygroup.FieldAPIKeyID, field.TypeInt64), sqlgraph.NewFieldSpec(apikeygroup.FieldGroupID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.APIKeyTable,
			Columns: []string{apikeygroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.APIKeyTable,
			Columns: []string{apikeygroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.GroupTable,
			Columns: []string{apikeygroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.GroupTable,
			Columns: []string{apikeygroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeygroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiKeyGroupUpdateOne is the builder for updating a single ApiKeyGroup entity.
type ApiKeyGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiKeyGroupMutation
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ApiKeyGroupUpdateOne) SetAPIKeyID(v int64) *ApiKeyGroupUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ApiKeyGroupUpdateOne) SetNillableAPIKeyID(v *int64) *ApiKeyGroupUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ApiKeyGroupUpdateOne) SetGroupID(v int64) *ApiKeyGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ApiKeyGroupUpdateOne) SetNillableGroupID(v *int64) *ApiKeyGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *ApiKeyGroupUpdateOne) SetAPIKey(v *APIKey) *ApiKeyGroupUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ApiKeyGroupUpdateOne) SetGroup(v *Group) *ApiKeyGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the ApiKeyGroupMutation object of the builder.
func (_u *ApiKeyGroupUpdateOne) Mutation() *ApiKeyGroupMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *ApiKeyGroupUpdateOne) ClearAPIKey() *ApiKeyGroupUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ApiKeyGroupUpdateOne) ClearGroup() *ApiKeyGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the ApiKeyGroupUpdate builder.
func (_u *ApiKeyGroupUpdateOne) Where(ps ...predicate.ApiKeyGroup) *ApiKeyGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiKeyGroupUpdateOne) Select(field string, fields ...string) *ApiKeyGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiKeyGroup entity.
func (_u *ApiKeyGroupUpdateOne) Save(ctx context.Context) (*ApiKeyGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyGroupUpdateOne) SaveX(ctx context.Context) *ApiKeyGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiKeyGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiKeyGroupUpdateOne) check() error {
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKeyGroup.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKeyGroup.group"`)
	}
	return nil
}

func (_u *ApiKeyGroupUpdateOne) sqlSave(ctx context.Context) (_node *ApiKeyGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeygroup.Table, apikeygroup.Columns, sqlgraph.NewFieldSpec(apikeygroup.FieldAPIKeyID, field.TypeInt64), sqlgraph.NewFieldSpec(apikeygroup.FieldGroupID, field.TypeInt64))
	if id, ok := _u.mutation.APIKeyID(); !ok {
		return nil, &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing "ApiKeyGroup.api_key_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "ApiKeyGroup.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !apikeygroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.APIKeyTable,
			Columns: []string{apikeygroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.APIKeyTable,
			Columns: []string{apikeygroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.GroupTable,
			Columns: []string{apikeygroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.GroupTable,
			Columns: []string{apikeygroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiKeyGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeygroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
