// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeygroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// ApiKeyGroupCreate is the builder for creating a ApiKeyGroup entity.
type ApiKeyGroupCreate struct {
	config
	mutation *ApiKeyGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ApiKeyGroupCreate) SetAPIKeyID(v int64) *ApiKeyGroupCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ApiKeyGroupCreate) SetGroupID(v int64) *ApiKeyGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApiKeyGroupCreate) SetCreatedAt(v time.Time) *ApiKeyGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApiKeyGroupCreate) SetNillableCreatedAt(v *time.Time) *ApiKeyGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *ApiKeyGroupCreate) SetAPIKey(v *APIKey) *ApiKeyGroupCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *ApiKeyGroupCreate) SetGroup(v *Group) *ApiKeyGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the ApiKeyGroupMutation object of the builder.
func (_c *ApiKeyGroupCreate) Mutation() *ApiKeyGroupMutation {
	return _c.mutation
}

// Save creates the ApiKeyGroup in the database.
func (_c *ApiKeyGroupCreate) Save(ctx context.Context) (*ApiKeyGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApiKeyGroupCreate) SaveX(ctx context.Context) *ApiKeyGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApiKeyGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApiKeyGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApiKeyGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikeygroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApiKeyGroupCreate) check() error {
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "ApiKeyGroup.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ApiKeyGroup.group_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ApiKeyGroup.created_at"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "ApiKeyGroup.api_key"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "ApiKeyGroup.group"`)}
	}
	return nil
}

func (_c *ApiKeyGroupCreate) sqlSave(ctx context.Context) (*ApiKeyGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *ApiKeyGroupCreate) createSpec() (*ApiKeyGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &ApiKeyGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeygroup.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeygroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.APIKeyTable,
			Columns: []string{apikeygroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeygroup.GroupTable,
			Columns: []string{apikeygroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ApiKeyGroup.Create().
//		SetAPIKeyID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ApiKeyGroupUpsert) {
//			SetAPIKeyID(v+v).
//		}).
//		Exec(ctx)
func (_c *ApiKeyGroupCreate) OnConflict(opts ...sql.ConflictOption) *ApiKeyGroupUpsertOne {
	_c.conflict = opts
	return &ApiKeyGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ApiKeyGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ApiKeyGroupCreate) OnConflictColumns(columns ...string) *ApiKeyGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ApiKeyGroupUpsertOne{
		create: _c,
	}
}

type (
	// ApiKeyGroupUpsertOne is the builder for "upsert"-ing
	//  one ApiKeyGroup node.
	ApiKeyGroupUpsertOne struct {
		create *ApiKeyGroupCreate
	}

	// ApiKeyGroupUpsert is the "OnConflict" setter.
	ApiKeyGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetAPIKeyID sets the "api_key_id" field.
func (u *ApiKeyGroupUpsert) SetAPIKeyID(v int64) *ApiKeyGroupUpsert {
	u.Set(apikeygroup.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ApiKeyGroupUpsert) UpdateAPIKeyID() *ApiKeyGroupUpsert {
	u.SetExcluded(apikeygroup.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ApiKeyGroupUpsert) SetGroupID(v int64) *ApiKeyGroupUpsert {
	u.Set(apikeygroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ApiKeyGroupUpsert) UpdateGroupID() *ApiKeyGroupUpsert {
	u.SetExcluded(apikeygroup.FieldGroupID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ApiKeyGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ApiKeyGroupUpsertOne) UpdateNewValues() *ApiKeyGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeygroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ApiKeyGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ApiKeyGroupUpsertOne) Ignore() *ApiKeyGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ApiKeyGroupUpsertOne) DoNothing() *ApiKeyGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ApiKeyGroupCreate.OnConflict
// documentation for more info.
func (u *ApiKeyGroupUpsertOne) Update(set func(*ApiKeyGroupUpsert)) *ApiKeyGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ApiKeyGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ApiKeyGroupUpsertOne) SetAPIKeyID(v int64) *ApiKeyGroupUpsertOne {
	return u.Update(func(s *ApiKeyGroupUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ApiKeyGroupUpsertOne) UpdateAPIKeyID() *ApiKeyGroupUpsertOne {
	return u.Update(func(s *ApiKeyGroupUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ApiKeyGroupUpsertOne) SetGroupID(v int64) *ApiKeyGroupUpsertOne {
	return u.Update(func(s *ApiKeyGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ApiKeyGroupUpsertOne) UpdateGroupID() *ApiKeyGroupUpsertOne {
	return u.Update(func(s *ApiKeyGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *ApiKeyGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ApiKeyGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ApiKeyGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// ApiKeyGroupCreateBulk is the builder for creating many ApiKeyGroup entities in bulk.
type ApiKeyGroupCreateBulk struct {
	config
	err      error
	builders []*ApiKeyGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the ApiKeyGroup entities in the database.
func (_c *ApiKeyGroupCreateBulk) Save(ctx context.Context) ([]*ApiKeyGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ApiKeyGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApiKeyGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApiKeyGroupCreateBulk) SaveX(ctx context.Context) []*ApiKeyGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApiKeyGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApiKeyGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ApiKeyGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ApiKeyGroupUpsert) {
//			SetAPIKeyID(v+v).
//		}).
//		Exec(ctx)
func (_c *ApiKeyGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *ApiKeyGroupUpsertBulk {
	_c.conflict = opts
	return &ApiKeyGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ApiKeyGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ApiKeyGroupCreateBulk) OnConflictColumns(columns ...string) *ApiKeyGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ApiKeyGroupUpsertBulk{
		create: _c,
	}
}

// ApiKeyGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of ApiKeyGroup nodes.
type ApiKeyGroupUpsertBulk struct {
	create *ApiKeyGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ApiKeyGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ApiKeyGroupUpsertBulk) UpdateNewValues() *ApiKeyGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeygroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ApiKeyGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ApiKeyGroupUpsertBulk) Ignore() *ApiKeyGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ApiKeyGroupUpsertBulk) DoNothing() *ApiKeyGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ApiKeyGroupCreateBulk.OnConflict
// documentation for more info.
func (u *ApiKeyGroupUpsertBulk) Update(set func(*ApiKeyGroupUpsert)) *ApiKeyGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ApiKeyGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ApiKeyGroupUpsertBulk) SetAPIKeyID(v int64) *ApiKeyGroupUpsertBulk {
	return u.Update(func(s *ApiKeyGroupUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ApiKeyGroupUpsertBulk) UpdateAPIKeyID() *ApiKeyGroupUpsertBulk {
	return u.Update(func(s *ApiKeyGroupUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ApiKeyGroupUpsertBulk) SetGroupID(v int64) *ApiKeyGroupUpsertBulk {
	return u.Update(func(s *ApiKeyGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ApiKeyGroupUpsertBulk) UpdateGroupID() *ApiKeyGroupUpsertBulk {
	return u.Update(func(s *ApiKeyGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *ApiKeyGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ApiKeyGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ApiKeyGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ApiKeyGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
