// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/useractivationjourney"
)

// UserActivationJourneyDelete is the builder for deleting a UserActivationJourney entity.
type UserActivationJourneyDelete struct {
	config
	hooks    []Hook
	mutation *UserActivationJourneyMutation
}

// Where appends a list predicates to the UserActivationJourneyDelete builder.
func (_d *UserActivationJourneyDelete) Where(ps ...predicate.UserActivationJourney) *UserActivationJourneyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserActivationJourneyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserActivationJourneyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserActivationJourneyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(useractivationjourney.Table, sqlgraph.NewFieldSpec(useractivationjourney.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserActivationJourneyDeleteOne is the builder for deleting a single UserActivationJourney entity.
type UserActivationJourneyDeleteOne struct {
	_d *UserActivationJourneyDelete
}

// Where appends a list predicates to the UserActivationJourneyDelete builder.
func (_d *UserActivationJourneyDeleteOne) Where(ps ...predicate.UserActivationJourney) *UserActivationJourneyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserActivationJourneyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useractivationjourney.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserActivationJourneyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
