// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/useractivationjourney"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UserActivationJourneyUpdate is the builder for updating UserActivationJourney entities.
type UserActivationJourneyUpdate struct {
	config
	hooks    []Hook
	mutation *UserActivationJourneyMutation
}

// Where appends a list predicates to the UserActivationJourneyUpdate builder.
func (_u *UserActivationJourneyUpdate) Where(ps ...predicate.UserActivationJourney) *UserActivationJourneyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserActivationJourneyUpdate) SetUpdatedAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserActivationJourneyUpdate) SetUserID(v int64) *UserActivationJourneyUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableUserID(v *int64) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCampaignSource sets the "campaign_source" field.
func (_u *UserActivationJourneyUpdate) SetCampaignSource(v string) *UserActivationJourneyUpdate {
	_u.mutation.SetCampaignSource(v)
	return _u
}

// SetNillableCampaignSource sets the "campaign_source" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableCampaignSource(v *string) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetCampaignSource(*v)
	}
	return _u
}

// SetStarterState sets the "starter_state" field.
func (_u *UserActivationJourneyUpdate) SetStarterState(v useractivationjourney.StarterState) *UserActivationJourneyUpdate {
	_u.mutation.SetStarterState(v)
	return _u
}

// SetNillableStarterState sets the "starter_state" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableStarterState(v *useractivationjourney.StarterState) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetStarterState(*v)
	}
	return _u
}

// SetStarterSubscriptionID sets the "starter_subscription_id" field.
func (_u *UserActivationJourneyUpdate) SetStarterSubscriptionID(v int64) *UserActivationJourneyUpdate {
	_u.mutation.SetStarterSubscriptionID(v)
	return _u
}

// SetNillableStarterSubscriptionID sets the "starter_subscription_id" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableStarterSubscriptionID(v *int64) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetStarterSubscriptionID(*v)
	}
	return _u
}

// ClearStarterSubscriptionID clears the value of the "starter_subscription_id" field.
func (_u *UserActivationJourneyUpdate) ClearStarterSubscriptionID() *UserActivationJourneyUpdate {
	_u.mutation.ClearStarterSubscriptionID()
	return _u
}

// SetStarterGrantedAt sets the "starter_granted_at" field.
func (_u *UserActivationJourneyUpdate) SetStarterGrantedAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetStarterGrantedAt(v)
	return _u
}

// SetNillableStarterGrantedAt sets the "starter_granted_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableStarterGrantedAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetStarterGrantedAt(*v)
	}
	return _u
}

// ClearStarterGrantedAt clears the value of the "starter_granted_at" field.
func (_u *UserActivationJourneyUpdate) ClearStarterGrantedAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearStarterGrantedAt()
	return _u
}

// SetStarterExpiresAt sets the "starter_expires_at" field.
func (_u *UserActivationJourneyUpdate) SetStarterExpiresAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetStarterExpiresAt(v)
	return _u
}

// SetNillableStarterExpiresAt sets the "starter_expires_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableStarterExpiresAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetStarterExpiresAt(*v)
	}
	return _u
}

// ClearStarterExpiresAt clears the value of the "starter_expires_at" field.
func (_u *UserActivationJourneyUpdate) ClearStarterExpiresAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearStarterExpiresAt()
	return _u
}

// SetRecallState sets the "recall_state" field.
func (_u *UserActivationJourneyUpdate) SetRecallState(v useractivationjourney.RecallState) *UserActivationJourneyUpdate {
	_u.mutation.SetRecallState(v)
	return _u
}

// SetNillableRecallState sets the "recall_state" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableRecallState(v *useractivationjourney.RecallState) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetRecallState(*v)
	}
	return _u
}

// SetRecallSubscriptionID sets the "recall_subscription_id" field.
func (_u *UserActivationJourneyUpdate) SetRecallSubscriptionID(v int64) *UserActivationJourneyUpdate {
	_u.mutation.SetRecallSubscriptionID(v)
	return _u
}

// SetNillableRecallSubscriptionID sets the "recall_subscription_id" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableRecallSubscriptionID(v *int64) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetRecallSubscriptionID(*v)
	}
	return _u
}

// ClearRecallSubscriptionID clears the value of the "recall_subscription_id" field.
func (_u *UserActivationJourneyUpdate) ClearRecallSubscriptionID() *UserActivationJourneyUpdate {
	_u.mutation.ClearRecallSubscriptionID()
	return _u
}

// SetRecallClaimedAt sets the "recall_claimed_at" field.
func (_u *UserActivationJourneyUpdate) SetRecallClaimedAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetRecallClaimedAt(v)
	return _u
}

// SetNillableRecallClaimedAt sets the "recall_claimed_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableRecallClaimedAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetRecallClaimedAt(*v)
	}
	return _u
}

// ClearRecallClaimedAt clears the value of the "recall_claimed_at" field.
func (_u *UserActivationJourneyUpdate) ClearRecallClaimedAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearRecallClaimedAt()
	return _u
}

// SetRecallExpiresAt sets the "recall_expires_at" field.
func (_u *UserActivationJourneyUpdate) SetRecallExpiresAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetRecallExpiresAt(v)
	return _u
}

// SetNillableRecallExpiresAt sets the "recall_expires_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableRecallExpiresAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetRecallExpiresAt(*v)
	}
	return _u
}

// ClearRecallExpiresAt clears the value of the "recall_expires_at" field.
func (_u *UserActivationJourneyUpdate) ClearRecallExpiresAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearRecallExpiresAt()
	return _u
}

// SetFirstSuccessAt sets the "first_success_at" field.
func (_u *UserActivationJourneyUpdate) SetFirstSuccessAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetFirstSuccessAt(v)
	return _u
}

// SetNillableFirstSuccessAt sets the "first_success_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableFirstSuccessAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetFirstSuccessAt(*v)
	}
	return _u
}

// ClearFirstSuccessAt clears the value of the "first_success_at" field.
func (_u *UserActivationJourneyUpdate) ClearFirstSuccessAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearFirstSuccessAt()
	return _u
}

// SetNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) SetNoAttemptEmailSentAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetNoAttemptEmailSentAt(v)
	return _u
}

// SetNillableNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableNoAttemptEmailSentAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetNoAttemptEmailSentAt(*v)
	}
	return _u
}

// ClearNoAttemptEmailSentAt clears the value of the "no_attempt_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) ClearNoAttemptEmailSentAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearNoAttemptEmailSentAt()
	return _u
}

// SetAttemptedEmailSentAt sets the "attempted_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) SetAttemptedEmailSentAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetAttemptedEmailSentAt(v)
	return _u
}

// SetNillableAttemptedEmailSentAt sets the "attempted_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableAttemptedEmailSentAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetAttemptedEmailSentAt(*v)
	}
	return _u
}

// ClearAttemptedEmailSentAt clears the value of the "attempted_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) ClearAttemptedEmailSentAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearAttemptedEmailSentAt()
	return _u
}

// SetPaidSupportEmailSentAt sets the "paid_support_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) SetPaidSupportEmailSentAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetPaidSupportEmailSentAt(v)
	return _u
}

// SetNillablePaidSupportEmailSentAt sets the "paid_support_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillablePaidSupportEmailSentAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetPaidSupportEmailSentAt(*v)
	}
	return _u
}

// ClearPaidSupportEmailSentAt clears the value of the "paid_support_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) ClearPaidSupportEmailSentAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearPaidSupportEmailSentAt()
	return _u
}

// SetRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) SetRecallAvailableEmailSentAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetRecallAvailableEmailSentAt(v)
	return _u
}

// SetNillableRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableRecallAvailableEmailSentAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetRecallAvailableEmailSentAt(*v)
	}
	return _u
}

// ClearRecallAvailableEmailSentAt clears the value of the "recall_available_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) ClearRecallAvailableEmailSentAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearRecallAvailableEmailSentAt()
	return _u
}

// SetRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) SetRecallExpiredEmailSentAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetRecallExpiredEmailSentAt(v)
	return _u
}

// SetNillableRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableRecallExpiredEmailSentAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetRecallExpiredEmailSentAt(*v)
	}
	return _u
}

// ClearRecallExpiredEmailSentAt clears the value of the "recall_expired_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) ClearRecallExpiredEmailSentAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearRecallExpiredEmailSentAt()
	return _u
}

// SetLastEmailSentAt sets the "last_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) SetLastEmailSentAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetLastEmailSentAt(v)
	return _u
}

// SetNillableLastEmailSentAt sets the "last_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableLastEmailSentAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetLastEmailSentAt(*v)
	}
	return _u
}

// ClearLastEmailSentAt clears the value of the "last_email_sent_at" field.
func (_u *UserActivationJourneyUpdate) ClearLastEmailSentAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearLastEmailSentAt()
	return _u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_u *UserActivationJourneyUpdate) SetLastEvaluatedAt(v time.Time) *UserActivationJourneyUpdate {
	_u.mutation.SetLastEvaluatedAt(v)
	return _u
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdate) SetNillableLastEvaluatedAt(v *time.Time) *UserActivationJourneyUpdate {
	if v != nil {
		_u.SetLastEvaluatedAt(*v)
	}
	return _u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (_u *UserActivationJourneyUpdate) ClearLastEvaluatedAt() *UserActivationJourneyUpdate {
	_u.mutation.ClearLastEvaluatedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserActivationJourneyUpdate) SetUser(v *User) *UserActivationJourneyUpdate {
	return _u.SetUserID(v.ID)
}

// SetStarterSubscription sets the "starter_subscription" edge to the UserSubscription entity.
func (_u *UserActivationJourneyUpdate) SetStarterSubscription(v *UserSubscription) *UserActivationJourneyUpdate {
	return _u.SetStarterSubscriptionID(v.ID)
}

// SetRecallSubscription sets the "recall_subscription" edge to the UserSubscription entity.
func (_u *UserActivationJourneyUpdate) SetRecallSubscription(v *UserSubscription) *UserActivationJourneyUpdate {
	return _u.SetRecallSubscriptionID(v.ID)
}

// Mutation returns the UserActivationJourneyMutation object of the builder.
func (_u *UserActivationJourneyUpdate) Mutation() *UserActivationJourneyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserActivationJourneyUpdate) ClearUser() *UserActivationJourneyUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearStarterSubscription clears the "starter_subscription" edge to the UserSubscription entity.
func (_u *UserActivationJourneyUpdate) ClearStarterSubscription() *UserActivationJourneyUpdate {
	_u.mutation.ClearStarterSubscription()
	return _u
}

// ClearRecallSubscription clears the "recall_subscription" edge to the UserSubscription entity.
func (_u *UserActivationJourneyUpdate) ClearRecallSubscription() *UserActivationJourneyUpdate {
	_u.mutation.ClearRecallSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserActivationJourneyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserActivationJourneyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserActivationJourneyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserActivationJourneyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserActivationJourneyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useractivationjourney.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserActivationJourneyUpdate) check() error {
	if v, ok := _u.mutation.CampaignSource(); ok {
		if err := useractivationjourney.CampaignSourceValidator(v); err != nil {
			return &ValidationError{Name: "campaign_source", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.campaign_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StarterState(); ok {
		if err := useractivationjourney.StarterStateValidator(v); err != nil {
			return &ValidationError{Name: "starter_state", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.starter_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecallState(); ok {
		if err := useractivationjourney.RecallStateValidator(v); err != nil {
			return &ValidationError{Name: "recall_state", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.recall_state": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserActivationJourney.user"`)
	}
	return nil
}

func (_u *UserActivationJourneyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useractivationjourney.Table, useractivationjourney.Columns, sqlgraph.NewFieldSpec(useractivationjourney.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useractivationjourney.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CampaignSource(); ok {
		_spec.SetField(useractivationjourney.FieldCampaignSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.StarterState(); ok {
		_spec.SetField(useractivationjourney.FieldStarterState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StarterGrantedAt(); ok {
		_spec.SetField(useractivationjourney.FieldStarterGrantedAt, field.TypeTime, value)
	}
	if _u.mutation.StarterGrantedAtCleared() {
		_spec.ClearField(useractivationjourney.FieldStarterGrantedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StarterExpiresAt(); ok {
		_spec.SetField(useractivationjourney.FieldStarterExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.StarterExpiresAtCleared() {
		_spec.ClearField(useractivationjourney.FieldStarterExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecallState(); ok {
		_spec.SetField(useractivationjourney.FieldRecallState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RecallClaimedAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.RecallClaimedAtCleared() {
		_spec.ClearField(useractivationjourney.FieldRecallClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecallExpiresAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.RecallExpiresAtCleared() {
		_spec.ClearField(useractivationjourney.FieldRecallExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FirstSuccessAt(); ok {
		_spec.SetField(useractivationjourney.FieldFirstSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.FirstSuccessAtCleared() {
		_spec.ClearField(useractivationjourney.FieldFirstSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NoAttemptEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldNoAttemptEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.NoAttemptEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldNoAttemptEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AttemptedEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldAttemptedEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.AttemptedEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldAttemptedEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PaidSupportEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldPaidSupportEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.PaidSupportEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldPaidSupportEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecallAvailableEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallAvailableEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.RecallAvailableEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldRecallAvailableEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecallExpiredEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallExpiredEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.RecallExpiredEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldRecallExpiredEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldLastEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.LastEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldLastEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(useractivationjourney.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(useractivationjourney.FieldLastEvaluatedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useractivationjourney.UserTable,
			Columns: []string{useractivationjourney.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useractivationjourney.UserTable,
			Columns: []string{useractivationjourney.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StarterSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.StarterSubscriptionTable,
			Columns: []string{useractivationjourney.StarterSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StarterSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.StarterSubscriptionTable,
			Columns: []string{useractivationjourney.StarterSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecallSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.RecallSubscriptionTable,
			Columns: []string{useractivationjourney.RecallSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecallSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.RecallSubscriptionTable,
			Columns: []string{useractivationjourney.RecallSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useractivationjourney.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserActivationJourneyUpdateOne is the builder for updating a single UserActivationJourney entity.
type UserActivationJourneyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserActivationJourneyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserActivationJourneyUpdateOne) SetUpdatedAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserActivationJourneyUpdateOne) SetUserID(v int64) *UserActivationJourneyUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableUserID(v *int64) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCampaignSource sets the "campaign_source" field.
func (_u *UserActivationJourneyUpdateOne) SetCampaignSource(v string) *UserActivationJourneyUpdateOne {
	_u.mutation.SetCampaignSource(v)
	return _u
}

// SetNillableCampaignSource sets the "campaign_source" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableCampaignSource(v *string) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetCampaignSource(*v)
	}
	return _u
}

// SetStarterState sets the "starter_state" field.
func (_u *UserActivationJourneyUpdateOne) SetStarterState(v useractivationjourney.StarterState) *UserActivationJourneyUpdateOne {
	_u.mutation.SetStarterState(v)
	return _u
}

// SetNillableStarterState sets the "starter_state" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableStarterState(v *useractivationjourney.StarterState) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetStarterState(*v)
	}
	return _u
}

// SetStarterSubscriptionID sets the "starter_subscription_id" field.
func (_u *UserActivationJourneyUpdateOne) SetStarterSubscriptionID(v int64) *UserActivationJourneyUpdateOne {
	_u.mutation.SetStarterSubscriptionID(v)
	return _u
}

// SetNillableStarterSubscriptionID sets the "starter_subscription_id" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableStarterSubscriptionID(v *int64) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetStarterSubscriptionID(*v)
	}
	return _u
}

// ClearStarterSubscriptionID clears the value of the "starter_subscription_id" field.
func (_u *UserActivationJourneyUpdateOne) ClearStarterSubscriptionID() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearStarterSubscriptionID()
	return _u
}

// SetStarterGrantedAt sets the "starter_granted_at" field.
func (_u *UserActivationJourneyUpdateOne) SetStarterGrantedAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetStarterGrantedAt(v)
	return _u
}

// SetNillableStarterGrantedAt sets the "starter_granted_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableStarterGrantedAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetStarterGrantedAt(*v)
	}
	return _u
}

// ClearStarterGrantedAt clears the value of the "starter_granted_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearStarterGrantedAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearStarterGrantedAt()
	return _u
}

// SetStarterExpiresAt sets the "starter_expires_at" field.
func (_u *UserActivationJourneyUpdateOne) SetStarterExpiresAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetStarterExpiresAt(v)
	return _u
}

// SetNillableStarterExpiresAt sets the "starter_expires_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableStarterExpiresAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetStarterExpiresAt(*v)
	}
	return _u
}

// ClearStarterExpiresAt clears the value of the "starter_expires_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearStarterExpiresAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearStarterExpiresAt()
	return _u
}

// SetRecallState sets the "recall_state" field.
func (_u *UserActivationJourneyUpdateOne) SetRecallState(v useractivationjourney.RecallState) *UserActivationJourneyUpdateOne {
	_u.mutation.SetRecallState(v)
	return _u
}

// SetNillableRecallState sets the "recall_state" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableRecallState(v *useractivationjourney.RecallState) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetRecallState(*v)
	}
	return _u
}

// SetRecallSubscriptionID sets the "recall_subscription_id" field.
func (_u *UserActivationJourneyUpdateOne) SetRecallSubscriptionID(v int64) *UserActivationJourneyUpdateOne {
	_u.mutation.SetRecallSubscriptionID(v)
	return _u
}

// SetNillableRecallSubscriptionID sets the "recall_subscription_id" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableRecallSubscriptionID(v *int64) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetRecallSubscriptionID(*v)
	}
	return _u
}

// ClearRecallSubscriptionID clears the value of the "recall_subscription_id" field.
func (_u *UserActivationJourneyUpdateOne) ClearRecallSubscriptionID() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearRecallSubscriptionID()
	return _u
}

// SetRecallClaimedAt sets the "recall_claimed_at" field.
func (_u *UserActivationJourneyUpdateOne) SetRecallClaimedAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetRecallClaimedAt(v)
	return _u
}

// SetNillableRecallClaimedAt sets the "recall_claimed_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableRecallClaimedAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetRecallClaimedAt(*v)
	}
	return _u
}

// ClearRecallClaimedAt clears the value of the "recall_claimed_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearRecallClaimedAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearRecallClaimedAt()
	return _u
}

// SetRecallExpiresAt sets the "recall_expires_at" field.
func (_u *UserActivationJourneyUpdateOne) SetRecallExpiresAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetRecallExpiresAt(v)
	return _u
}

// SetNillableRecallExpiresAt sets the "recall_expires_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableRecallExpiresAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetRecallExpiresAt(*v)
	}
	return _u
}

// ClearRecallExpiresAt clears the value of the "recall_expires_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearRecallExpiresAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearRecallExpiresAt()
	return _u
}

// SetFirstSuccessAt sets the "first_success_at" field.
func (_u *UserActivationJourneyUpdateOne) SetFirstSuccessAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetFirstSuccessAt(v)
	return _u
}

// SetNillableFirstSuccessAt sets the "first_success_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableFirstSuccessAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetFirstSuccessAt(*v)
	}
	return _u
}

// ClearFirstSuccessAt clears the value of the "first_success_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearFirstSuccessAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearFirstSuccessAt()
	return _u
}

// SetNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) SetNoAttemptEmailSentAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetNoAttemptEmailSentAt(v)
	return _u
}

// SetNillableNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableNoAttemptEmailSentAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetNoAttemptEmailSentAt(*v)
	}
	return _u
}

// ClearNoAttemptEmailSentAt clears the value of the "no_attempt_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearNoAttemptEmailSentAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearNoAttemptEmailSentAt()
	return _u
}

// SetAttemptedEmailSentAt sets the "attempted_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) SetAttemptedEmailSentAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetAttemptedEmailSentAt(v)
	return _u
}

// SetNillableAttemptedEmailSentAt sets the "attempted_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableAttemptedEmailSentAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetAttemptedEmailSentAt(*v)
	}
	return _u
}

// ClearAttemptedEmailSentAt clears the value of the "attempted_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearAttemptedEmailSentAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearAttemptedEmailSentAt()
	return _u
}

// SetPaidSupportEmailSentAt sets the "paid_support_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) SetPaidSupportEmailSentAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetPaidSupportEmailSentAt(v)
	return _u
}

// SetNillablePaidSupportEmailSentAt sets the "paid_support_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillablePaidSupportEmailSentAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetPaidSupportEmailSentAt(*v)
	}
	return _u
}

// ClearPaidSupportEmailSentAt clears the value of the "paid_support_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearPaidSupportEmailSentAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearPaidSupportEmailSentAt()
	return _u
}

// SetRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) SetRecallAvailableEmailSentAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetRecallAvailableEmailSentAt(v)
	return _u
}

// SetNillableRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableRecallAvailableEmailSentAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetRecallAvailableEmailSentAt(*v)
	}
	return _u
}

// ClearRecallAvailableEmailSentAt clears the value of the "recall_available_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearRecallAvailableEmailSentAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearRecallAvailableEmailSentAt()
	return _u
}

// SetRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) SetRecallExpiredEmailSentAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetRecallExpiredEmailSentAt(v)
	return _u
}

// SetNillableRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableRecallExpiredEmailSentAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetRecallExpiredEmailSentAt(*v)
	}
	return _u
}

// ClearRecallExpiredEmailSentAt clears the value of the "recall_expired_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearRecallExpiredEmailSentAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearRecallExpiredEmailSentAt()
	return _u
}

// SetLastEmailSentAt sets the "last_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) SetLastEmailSentAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetLastEmailSentAt(v)
	return _u
}

// SetNillableLastEmailSentAt sets the "last_email_sent_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableLastEmailSentAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetLastEmailSentAt(*v)
	}
	return _u
}

// ClearLastEmailSentAt clears the value of the "last_email_sent_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearLastEmailSentAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearLastEmailSentAt()
	return _u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_u *UserActivationJourneyUpdateOne) SetLastEvaluatedAt(v time.Time) *UserActivationJourneyUpdateOne {
	_u.mutation.SetLastEvaluatedAt(v)
	return _u
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_u *UserActivationJourneyUpdateOne) SetNillableLastEvaluatedAt(v *time.Time) *UserActivationJourneyUpdateOne {
	if v != nil {
		_u.SetLastEvaluatedAt(*v)
	}
	return _u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (_u *UserActivationJourneyUpdateOne) ClearLastEvaluatedAt() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearLastEvaluatedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserActivationJourneyUpdateOne) SetUser(v *User) *UserActivationJourneyUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetStarterSubscription sets the "starter_subscription" edge to the UserSubscription entity.
func (_u *UserActivationJourneyUpdateOne) SetStarterSubscription(v *UserSubscription) *UserActivationJourneyUpdateOne {
	return _u.SetStarterSubscriptionID(v.ID)
}

// SetRecallSubscription sets the "recall_subscription" edge to the UserSubscription entity.
func (_u *UserActivationJourneyUpdateOne) SetRecallSubscription(v *UserSubscription) *UserActivationJourneyUpdateOne {
	return _u.SetRecallSubscriptionID(v.ID)
}

// Mutation returns the UserActivationJourneyMutation object of the builder.
func (_u *UserActivationJourneyUpdateOne) Mutation() *UserActivationJourneyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserActivationJourneyUpdateOne) ClearUser() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearStarterSubscription clears the "starter_subscription" edge to the UserSubscription entity.
func (_u *UserActivationJourneyUpdateOne) ClearStarterSubscription() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearStarterSubscription()
	return _u
}

// ClearRecallSubscription clears the "recall_subscription" edge to the UserSubscription entity.
func (_u *UserActivationJourneyUpdateOne) ClearRecallSubscription() *UserActivationJourneyUpdateOne {
	_u.mutation.ClearRecallSubscription()
	return _u
}

// Where appends a list predicates to the UserActivationJourneyUpdate builder.
func (_u *UserActivationJourneyUpdateOne) Where(ps ...predicate.UserActivationJourney) *UserActivationJourneyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserActivationJourneyUpdateOne) Select(field string, fields ...string) *UserActivationJourneyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserActivationJourney entity.
func (_u *UserActivationJourneyUpdateOne) Save(ctx context.Context) (*UserActivationJourney, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserActivationJourneyUpdateOne) SaveX(ctx context.Context) *UserActivationJourney {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserActivationJourneyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserActivationJourneyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserActivationJourneyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useractivationjourney.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserActivationJourneyUpdateOne) check() error {
	if v, ok := _u.mutation.CampaignSource(); ok {
		if err := useractivationjourney.CampaignSourceValidator(v); err != nil {
			return &ValidationError{Name: "campaign_source", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.campaign_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StarterState(); ok {
		if err := useractivationjourney.StarterStateValidator(v); err != nil {
			return &ValidationError{Name: "starter_state", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.starter_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecallState(); ok {
		if err := useractivationjourney.RecallStateValidator(v); err != nil {
			return &ValidationError{Name: "recall_state", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.recall_state": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserActivationJourney.user"`)
	}
	return nil
}

func (_u *UserActivationJourneyUpdateOne) sqlSave(ctx context.Context) (_node *UserActivationJourney, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useractivationjourney.Table, useractivationjourney.Columns, sqlgraph.NewFieldSpec(useractivationjourney.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserActivationJourney.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useractivationjourney.FieldID)
		for _, f := range fields {
			if !useractivationjourney.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useractivationjourney.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useractivationjourney.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CampaignSource(); ok {
		_spec.SetField(useractivationjourney.FieldCampaignSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.StarterState(); ok {
		_spec.SetField(useractivationjourney.FieldStarterState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StarterGrantedAt(); ok {
		_spec.SetField(useractivationjourney.FieldStarterGrantedAt, field.TypeTime, value)
	}
	if _u.mutation.StarterGrantedAtCleared() {
		_spec.ClearField(useractivationjourney.FieldStarterGrantedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StarterExpiresAt(); ok {
		_spec.SetField(useractivationjourney.FieldStarterExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.StarterExpiresAtCleared() {
		_spec.ClearField(useractivationjourney.FieldStarterExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecallState(); ok {
		_spec.SetField(useractivationjourney.FieldRecallState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RecallClaimedAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.RecallClaimedAtCleared() {
		_spec.ClearField(useractivationjourney.FieldRecallClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecallExpiresAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.RecallExpiresAtCleared() {
		_spec.ClearField(useractivationjourney.FieldRecallExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FirstSuccessAt(); ok {
		_spec.SetField(useractivationjourney.FieldFirstSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.FirstSuccessAtCleared() {
		_spec.ClearField(useractivationjourney.FieldFirstSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NoAttemptEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldNoAttemptEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.NoAttemptEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldNoAttemptEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AttemptedEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldAttemptedEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.AttemptedEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldAttemptedEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PaidSupportEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldPaidSupportEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.PaidSupportEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldPaidSupportEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecallAvailableEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallAvailableEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.RecallAvailableEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldRecallAvailableEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RecallExpiredEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallExpiredEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.RecallExpiredEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldRecallExpiredEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldLastEmailSentAt, field.TypeTime, value)
	}
	if _u.mutation.LastEmailSentAtCleared() {
		_spec.ClearField(useractivationjourney.FieldLastEmailSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(useractivationjourney.FieldLastEvaluatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEvaluatedAtCleared() {
		_spec.ClearField(useractivationjourney.FieldLastEvaluatedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useractivationjourney.UserTable,
			Columns: []string{useractivationjourney.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useractivationjourney.UserTable,
			Columns: []string{useractivationjourney.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StarterSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.StarterSubscriptionTable,
			Columns: []string{useractivationjourney.StarterSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StarterSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.StarterSubscriptionTable,
			Columns: []string{useractivationjourney.StarterSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecallSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.RecallSubscriptionTable,
			Columns: []string{useractivationjourney.RecallSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecallSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.RecallSubscriptionTable,
			Columns: []string{useractivationjourney.RecallSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserActivationJourney{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useractivationjourney.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
