// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/useractivationjourney"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UserActivationJourneyQuery is the builder for querying UserActivationJourney entities.
type UserActivationJourneyQuery struct {
	config
	ctx                     *QueryContext
	order                   []useractivationjourney.OrderOption
	inters                  []Interceptor
	predicates              []predicate.UserActivationJourney
	withUser                *UserQuery
	withStarterSubscription *UserSubscriptionQuery
	withRecallSubscription  *UserSubscriptionQuery
	modifiers               []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserActivationJourneyQuery builder.
func (_q *UserActivationJourneyQuery) Where(ps ...predicate.UserActivationJourney) *UserActivationJourneyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UserActivationJourneyQuery) Limit(limit int) *UserActivationJourneyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UserActivationJourneyQuery) Offset(offset int) *UserActivationJourneyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UserActivationJourneyQuery) Unique(unique bool) *UserActivationJourneyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UserActivationJourneyQuery) Order(o ...useractivationjourney.OrderOption) *UserActivationJourneyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *UserActivationJourneyQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(useractivationjourney.Table, useractivationjourney.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, useractivationjourney.UserTable, useractivationjourney.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStarterSubscription chains the current query on the "starter_subscription" edge.
func (_q *UserActivationJourneyQuery) QueryStarterSubscription() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(useractivationjourney.Table, useractivationjourney.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, useractivationjourney.StarterSubscriptionTable, useractivationjourney.StarterSubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRecallSubscription chains the current query on the "recall_subscription" edge.
func (_q *UserActivationJourneyQuery) QueryRecallSubscription() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(useractivationjourney.Table, useractivationjourney.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, useractivationjourney.RecallSubscriptionTable, useractivationjourney.RecallSubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserActivationJourney entity from the query.
// Returns a *NotFoundError when no UserActivationJourney was found.
func (_q *UserActivationJourneyQuery) First(ctx context.Context) (*UserActivationJourney, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{useractivationjourney.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UserActivationJourneyQuery) FirstX(ctx context.Context) *UserActivationJourney {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserActivationJourney ID from the query.
// Returns a *NotFoundError when no UserActivationJourney ID was found.
func (_q *UserActivationJourneyQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{useractivationjourney.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UserActivationJourneyQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserActivationJourney entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserActivationJourney entity is found.
// Returns a *NotFoundError when no UserActivationJourney entities are found.
func (_q *UserActivationJourneyQuery) Only(ctx context.Context) (*UserActivationJourney, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{useractivationjourney.Label}
	default:
		return nil, &NotSingularError{useractivationjourney.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UserActivationJourneyQuery) OnlyX(ctx context.Context) *UserActivationJourney {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserActivationJourney ID in the query.
// Returns a *NotSingularError when more than one UserActivationJourney ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UserActivationJourneyQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{useractivationjourney.Label}
	default:
		err = &NotSingularError{useractivationjourney.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UserActivationJourneyQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserActivationJourneys.
func (_q *UserActivationJourneyQuery) All(ctx context.Context) ([]*UserActivationJourney, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserActivationJourney, *UserActivationJourneyQuery]()
	return withInterceptors[[]*UserActivationJourney](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UserActivationJourneyQuery) AllX(ctx context.Context) []*UserActivationJourney {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserActivationJourney IDs.
func (_q *UserActivationJourneyQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(useractivationjourney.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UserActivationJourneyQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UserActivationJourneyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UserActivationJourneyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UserActivationJourneyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UserActivationJourneyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UserActivationJourneyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserActivationJourneyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UserActivationJourneyQuery) Clone() *UserActivationJourneyQuery {
	if _q == nil {
		return nil
	}
	return &UserActivationJourneyQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]useractivationjourney.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.UserActivationJourney{}, _q.predicates...),
		withUser:                _q.withUser.Clone(),
		withStarterSubscription: _q.withStarterSubscription.Clone(),
		withRecallSubscription:  _q.withRecallSubscription.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserActivationJourneyQuery) WithUser(opts ...func(*UserQuery)) *UserActivationJourneyQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithStarterSubscription tells the query-builder to eager-load the nodes that are connected to
// the "starter_subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserActivationJourneyQuery) WithStarterSubscription(opts ...func(*UserSubscriptionQuery)) *UserActivationJourneyQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStarterSubscription = query
	return _q
}

// WithRecallSubscription tells the query-builder to eager-load the nodes that are connected to
// the "recall_subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserActivationJourneyQuery) WithRecallSubscription(opts ...func(*UserSubscriptionQuery)) *UserActivationJourneyQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRecallSubscription = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserActivationJourney.Query().
//		GroupBy(useractivationjourney.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UserActivationJourneyQuery) GroupBy(field string, fields ...string) *UserActivationJourneyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserActivationJourneyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = useractivationjourney.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UserActivationJourney.Query().
//		Select(useractivationjourney.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *UserActivationJourneyQuery) Select(fields ...string) *UserActivationJourneySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UserActivationJourneySelect{UserActivationJourneyQuery: _q}
	sbuild.label = useractivationjourney.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserActivationJourneySelect configured with the given aggregations.
func (_q *UserActivationJourneyQuery) Aggregate(fns ...AggregateFunc) *UserActivationJourneySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UserActivationJourneyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !useractivationjourney.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UserActivationJourneyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserActivationJourney, error) {
	var (
		nodes       = []*UserActivationJourney{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUser != nil,
			_q.withStarterSubscription != nil,
			_q.withRecallSubscription != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserActivationJourney).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserActivationJourney{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *UserActivationJourney, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStarterSubscription; query != nil {
		if err := _q.loadStarterSubscription(ctx, query, nodes, nil,
			func(n *UserActivationJourney, e *UserSubscription) { n.Edges.StarterSubscription = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRecallSubscription; query != nil {
		if err := _q.loadRecallSubscription(ctx, query, nodes, nil,
			func(n *UserActivationJourney, e *UserSubscription) { n.Edges.RecallSubscription = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UserActivationJourneyQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserActivationJourney, init func(*UserActivationJourney), assign func(*UserActivationJourney, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserActivationJourney)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UserActivationJourneyQuery) loadStarterSubscription(ctx context.Context, query *UserSubscriptionQuery, nodes []*UserActivationJourney, init func(*UserActivationJourney), assign func(*UserActivationJourney, *UserSubscription)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserActivationJourney)
	for i := range nodes {
		if nodes[i].StarterSubscriptionID == nil {
			continue
		}
		fk := *nodes[i].StarterSubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usersubscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "starter_subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UserActivationJourneyQuery) loadRecallSubscription(ctx context.Context, query *UserSubscriptionQuery, nodes []*UserActivationJourney, init func(*UserActivationJourney), assign func(*UserActivationJourney, *UserSubscription)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserActivationJourney)
	for i := range nodes {
		if nodes[i].RecallSubscriptionID == nil {
			continue
		}
		fk := *nodes[i].RecallSubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usersubscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "recall_subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *UserActivationJourneyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UserActivationJourneyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(useractivationjourney.Table, useractivationjourney.Columns, sqlgraph.NewFieldSpec(useractivationjourney.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useractivationjourney.FieldID)
		for i := range fields {
			if fields[i] != useractivationjourney.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(useractivationjourney.FieldUserID)
		}
		if _q.withStarterSubscription != nil {
			_spec.Node.AddColumnOnce(useractivationjourney.FieldStarterSubscriptionID)
		}
		if _q.withRecallSubscription != nil {
			_spec.Node.AddColumnOnce(useractivationjourney.FieldRecallSubscriptionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UserActivationJourneyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(useractivationjourney.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = useractivationjourney.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *UserActivationJourneyQuery) ForUpdate(opts ...sql.LockOption) *UserActivationJourneyQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *UserActivationJourneyQuery) ForShare(opts ...sql.LockOption) *UserActivationJourneyQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// UserActivationJourneyGroupBy is the group-by builder for UserActivationJourney entities.
type UserActivationJourneyGroupBy struct {
	selector
	build *UserActivationJourneyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UserActivationJourneyGroupBy) Aggregate(fns ...AggregateFunc) *UserActivationJourneyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UserActivationJourneyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserActivationJourneyQuery, *UserActivationJourneyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UserActivationJourneyGroupBy) sqlScan(ctx context.Context, root *UserActivationJourneyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserActivationJourneySelect is the builder for selecting fields of UserActivationJourney entities.
type UserActivationJourneySelect struct {
	*UserActivationJourneyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UserActivationJourneySelect) Aggregate(fns ...AggregateFunc) *UserActivationJourneySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UserActivationJourneySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserActivationJourneyQuery, *UserActivationJourneySelect](ctx, _s.UserActivationJourneyQuery, _s, _s.inters, v)
}

func (_s *UserActivationJourneySelect) sqlScan(ctx context.Context, root *UserActivationJourneyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
