// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/useractivationjourney"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UserActivationJourneyCreate is the builder for creating a UserActivationJourney entity.
type UserActivationJourneyCreate struct {
	config
	mutation *UserActivationJourneyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserActivationJourneyCreate) SetCreatedAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableCreatedAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserActivationJourneyCreate) SetUpdatedAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableUpdatedAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserActivationJourneyCreate) SetUserID(v int64) *UserActivationJourneyCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCampaignSource sets the "campaign_source" field.
func (_c *UserActivationJourneyCreate) SetCampaignSource(v string) *UserActivationJourneyCreate {
	_c.mutation.SetCampaignSource(v)
	return _c
}

// SetNillableCampaignSource sets the "campaign_source" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableCampaignSource(v *string) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetCampaignSource(*v)
	}
	return _c
}

// SetStarterState sets the "starter_state" field.
func (_c *UserActivationJourneyCreate) SetStarterState(v useractivationjourney.StarterState) *UserActivationJourneyCreate {
	_c.mutation.SetStarterState(v)
	return _c
}

// SetNillableStarterState sets the "starter_state" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableStarterState(v *useractivationjourney.StarterState) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetStarterState(*v)
	}
	return _c
}

// SetStarterSubscriptionID sets the "starter_subscription_id" field.
func (_c *UserActivationJourneyCreate) SetStarterSubscriptionID(v int64) *UserActivationJourneyCreate {
	_c.mutation.SetStarterSubscriptionID(v)
	return _c
}

// SetNillableStarterSubscriptionID sets the "starter_subscription_id" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableStarterSubscriptionID(v *int64) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetStarterSubscriptionID(*v)
	}
	return _c
}

// SetStarterGrantedAt sets the "starter_granted_at" field.
func (_c *UserActivationJourneyCreate) SetStarterGrantedAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetStarterGrantedAt(v)
	return _c
}

// SetNillableStarterGrantedAt sets the "starter_granted_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableStarterGrantedAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetStarterGrantedAt(*v)
	}
	return _c
}

// SetStarterExpiresAt sets the "starter_expires_at" field.
func (_c *UserActivationJourneyCreate) SetStarterExpiresAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetStarterExpiresAt(v)
	return _c
}

// SetNillableStarterExpiresAt sets the "starter_expires_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableStarterExpiresAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetStarterExpiresAt(*v)
	}
	return _c
}

// SetRecallState sets the "recall_state" field.
func (_c *UserActivationJourneyCreate) SetRecallState(v useractivationjourney.RecallState) *UserActivationJourneyCreate {
	_c.mutation.SetRecallState(v)
	return _c
}

// SetNillableRecallState sets the "recall_state" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableRecallState(v *useractivationjourney.RecallState) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetRecallState(*v)
	}
	return _c
}

// SetRecallSubscriptionID sets the "recall_subscription_id" field.
func (_c *UserActivationJourneyCreate) SetRecallSubscriptionID(v int64) *UserActivationJourneyCreate {
	_c.mutation.SetRecallSubscriptionID(v)
	return _c
}

// SetNillableRecallSubscriptionID sets the "recall_subscription_id" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableRecallSubscriptionID(v *int64) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetRecallSubscriptionID(*v)
	}
	return _c
}

// SetRecallClaimedAt sets the "recall_claimed_at" field.
func (_c *UserActivationJourneyCreate) SetRecallClaimedAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetRecallClaimedAt(v)
	return _c
}

// SetNillableRecallClaimedAt sets the "recall_claimed_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableRecallClaimedAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetRecallClaimedAt(*v)
	}
	return _c
}

// SetRecallExpiresAt sets the "recall_expires_at" field.
func (_c *UserActivationJourneyCreate) SetRecallExpiresAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetRecallExpiresAt(v)
	return _c
}

// SetNillableRecallExpiresAt sets the "recall_expires_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableRecallExpiresAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetRecallExpiresAt(*v)
	}
	return _c
}

// SetFirstSuccessAt sets the "first_success_at" field.
func (_c *UserActivationJourneyCreate) SetFirstSuccessAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetFirstSuccessAt(v)
	return _c
}

// SetNillableFirstSuccessAt sets the "first_success_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableFirstSuccessAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetFirstSuccessAt(*v)
	}
	return _c
}

// SetNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field.
func (_c *UserActivationJourneyCreate) SetNoAttemptEmailSentAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetNoAttemptEmailSentAt(v)
	return _c
}

// SetNillableNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableNoAttemptEmailSentAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetNoAttemptEmailSentAt(*v)
	}
	return _c
}

// SetAttemptedEmailSentAt sets the "attempted_email_sent_at" field.
func (_c *UserActivationJourneyCreate) SetAttemptedEmailSentAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetAttemptedEmailSentAt(v)
	return _c
}

// SetNillableAttemptedEmailSentAt sets the "attempted_email_sent_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableAttemptedEmailSentAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetAttemptedEmailSentAt(*v)
	}
	return _c
}

// SetPaidSupportEmailSentAt sets the "paid_support_email_sent_at" field.
func (_c *UserActivationJourneyCreate) SetPaidSupportEmailSentAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetPaidSupportEmailSentAt(v)
	return _c
}

// SetNillablePaidSupportEmailSentAt sets the "paid_support_email_sent_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillablePaidSupportEmailSentAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetPaidSupportEmailSentAt(*v)
	}
	return _c
}

// SetRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field.
func (_c *UserActivationJourneyCreate) SetRecallAvailableEmailSentAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetRecallAvailableEmailSentAt(v)
	return _c
}

// SetNillableRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableRecallAvailableEmailSentAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetRecallAvailableEmailSentAt(*v)
	}
	return _c
}

// SetRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field.
func (_c *UserActivationJourneyCreate) SetRecallExpiredEmailSentAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetRecallExpiredEmailSentAt(v)
	return _c
}

// SetNillableRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableRecallExpiredEmailSentAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetRecallExpiredEmailSentAt(*v)
	}
	return _c
}

// SetLastEmailSentAt sets the "last_email_sent_at" field.
func (_c *UserActivationJourneyCreate) SetLastEmailSentAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetLastEmailSentAt(v)
	return _c
}

// SetNillableLastEmailSentAt sets the "last_email_sent_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableLastEmailSentAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetLastEmailSentAt(*v)
	}
	return _c
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (_c *UserActivationJourneyCreate) SetLastEvaluatedAt(v time.Time) *UserActivationJourneyCreate {
	_c.mutation.SetLastEvaluatedAt(v)
	return _c
}

// SetNillableLastEvaluatedAt sets the "last_evaluated_at" field if the given value is not nil.
func (_c *UserActivationJourneyCreate) SetNillableLastEvaluatedAt(v *time.Time) *UserActivationJourneyCreate {
	if v != nil {
		_c.SetLastEvaluatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserActivationJourneyCreate) SetUser(v *User) *UserActivationJourneyCreate {
	return _c.SetUserID(v.ID)
}

// SetStarterSubscription sets the "starter_subscription" edge to the UserSubscription entity.
func (_c *UserActivationJourneyCreate) SetStarterSubscription(v *UserSubscription) *UserActivationJourneyCreate {
	return _c.SetStarterSubscriptionID(v.ID)
}

// SetRecallSubscription sets the "recall_subscription" edge to the UserSubscription entity.
func (_c *UserActivationJourneyCreate) SetRecallSubscription(v *UserSubscription) *UserActivationJourneyCreate {
	return _c.SetRecallSubscriptionID(v.ID)
}

// Mutation returns the UserActivationJourneyMutation object of the builder.
func (_c *UserActivationJourneyCreate) Mutation() *UserActivationJourneyMutation {
	return _c.mutation
}

// Save creates the UserActivationJourney in the database.
func (_c *UserActivationJourneyCreate) Save(ctx context.Context) (*UserActivationJourney, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserActivationJourneyCreate) SaveX(ctx context.Context) *UserActivationJourney {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserActivationJourneyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserActivationJourneyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserActivationJourneyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := useractivationjourney.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := useractivationjourney.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CampaignSource(); !ok {
		v := useractivationjourney.DefaultCampaignSource
		_c.mutation.SetCampaignSource(v)
	}
	if _, ok := _c.mutation.StarterState(); !ok {
		v := useractivationjourney.DefaultStarterState
		_c.mutation.SetStarterState(v)
	}
	if _, ok := _c.mutation.RecallState(); !ok {
		v := useractivationjourney.DefaultRecallState
		_c.mutation.SetRecallState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserActivationJourneyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserActivationJourney.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserActivationJourney.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserActivationJourney.user_id"`)}
	}
	if _, ok := _c.mutation.CampaignSource(); !ok {
		return &ValidationError{Name: "campaign_source", err: errors.New(`ent: missing required field "UserActivationJourney.campaign_source"`)}
	}
	if v, ok := _c.mutation.CampaignSource(); ok {
		if err := useractivationjourney.CampaignSourceValidator(v); err != nil {
			return &ValidationError{Name: "campaign_source", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.campaign_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StarterState(); !ok {
		return &ValidationError{Name: "starter_state", err: errors.New(`ent: missing required field "UserActivationJourney.starter_state"`)}
	}
	if v, ok := _c.mutation.StarterState(); ok {
		if err := useractivationjourney.StarterStateValidator(v); err != nil {
			return &ValidationError{Name: "starter_state", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.starter_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecallState(); !ok {
		return &ValidationError{Name: "recall_state", err: errors.New(`ent: missing required field "UserActivationJourney.recall_state"`)}
	}
	if v, ok := _c.mutation.RecallState(); ok {
		if err := useractivationjourney.RecallStateValidator(v); err != nil {
			return &ValidationError{Name: "recall_state", err: fmt.Errorf(`ent: validator failed for field "UserActivationJourney.recall_state": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserActivationJourney.user"`)}
	}
	return nil
}

func (_c *UserActivationJourneyCreate) sqlSave(ctx context.Context) (*UserActivationJourney, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserActivationJourneyCreate) createSpec() (*UserActivationJourney, *sqlgraph.CreateSpec) {
	var (
		_node = &UserActivationJourney{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(useractivationjourney.Table, sqlgraph.NewFieldSpec(useractivationjourney.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(useractivationjourney.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(useractivationjourney.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CampaignSource(); ok {
		_spec.SetField(useractivationjourney.FieldCampaignSource, field.TypeString, value)
		_node.CampaignSource = value
	}
	if value, ok := _c.mutation.StarterState(); ok {
		_spec.SetField(useractivationjourney.FieldStarterState, field.TypeEnum, value)
		_node.StarterState = value
	}
	if value, ok := _c.mutation.StarterGrantedAt(); ok {
		_spec.SetField(useractivationjourney.FieldStarterGrantedAt, field.TypeTime, value)
		_node.StarterGrantedAt = &value
	}
	if value, ok := _c.mutation.StarterExpiresAt(); ok {
		_spec.SetField(useractivationjourney.FieldStarterExpiresAt, field.TypeTime, value)
		_node.StarterExpiresAt = &value
	}
	if value, ok := _c.mutation.RecallState(); ok {
		_spec.SetField(useractivationjourney.FieldRecallState, field.TypeEnum, value)
		_node.RecallState = value
	}
	if value, ok := _c.mutation.RecallClaimedAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallClaimedAt, field.TypeTime, value)
		_node.RecallClaimedAt = &value
	}
	if value, ok := _c.mutation.RecallExpiresAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallExpiresAt, field.TypeTime, value)
		_node.RecallExpiresAt = &value
	}
	if value, ok := _c.mutation.FirstSuccessAt(); ok {
		_spec.SetField(useractivationjourney.FieldFirstSuccessAt, field.TypeTime, value)
		_node.FirstSuccessAt = &value
	}
	if value, ok := _c.mutation.NoAttemptEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldNoAttemptEmailSentAt, field.TypeTime, value)
		_node.NoAttemptEmailSentAt = &value
	}
	if value, ok := _c.mutation.AttemptedEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldAttemptedEmailSentAt, field.TypeTime, value)
		_node.AttemptedEmailSentAt = &value
	}
	if value, ok := _c.mutation.PaidSupportEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldPaidSupportEmailSentAt, field.TypeTime, value)
		_node.PaidSupportEmailSentAt = &value
	}
	if value, ok := _c.mutation.RecallAvailableEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallAvailableEmailSentAt, field.TypeTime, value)
		_node.RecallAvailableEmailSentAt = &value
	}
	if value, ok := _c.mutation.RecallExpiredEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldRecallExpiredEmailSentAt, field.TypeTime, value)
		_node.RecallExpiredEmailSentAt = &value
	}
	if value, ok := _c.mutation.LastEmailSentAt(); ok {
		_spec.SetField(useractivationjourney.FieldLastEmailSentAt, field.TypeTime, value)
		_node.LastEmailSentAt = &value
	}
	if value, ok := _c.mutation.LastEvaluatedAt(); ok {
		_spec.SetField(useractivationjourney.FieldLastEvaluatedAt, field.TypeTime, value)
		_node.LastEvaluatedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   useractivationjourney.UserTable,
			Columns: []string{useractivationjourney.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StarterSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.StarterSubscriptionTable,
			Columns: []string{useractivationjourney.StarterSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StarterSubscriptionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecallSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   useractivationjourney.RecallSubscriptionTable,
			Columns: []string{useractivationjourney.RecallSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecallSubscriptionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserActivationJourney.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserActivationJourneyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserActivationJourneyCreate) OnConflict(opts ...sql.ConflictOption) *UserActivationJourneyUpsertOne {
	_c.conflict = opts
	return &UserActivationJourneyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserActivationJourney.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserActivationJourneyCreate) OnConflictColumns(columns ...string) *UserActivationJourneyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserActivationJourneyUpsertOne{
		create: _c,
	}
}

type (
	// UserActivationJourneyUpsertOne is the builder for "upsert"-ing
	//  one UserActivationJourney node.
	UserActivationJourneyUpsertOne struct {
		create *UserActivationJourneyCreate
	}

	// UserActivationJourneyUpsert is the "OnConflict" setter.
	UserActivationJourneyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserActivationJourneyUpsert) SetUpdatedAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateUpdatedAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserActivationJourneyUpsert) SetUserID(v int64) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateUserID() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldUserID)
	return u
}

// SetCampaignSource sets the "campaign_source" field.
func (u *UserActivationJourneyUpsert) SetCampaignSource(v string) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldCampaignSource, v)
	return u
}

// UpdateCampaignSource sets the "campaign_source" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateCampaignSource() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldCampaignSource)
	return u
}

// SetStarterState sets the "starter_state" field.
func (u *UserActivationJourneyUpsert) SetStarterState(v useractivationjourney.StarterState) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldStarterState, v)
	return u
}

// UpdateStarterState sets the "starter_state" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateStarterState() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldStarterState)
	return u
}

// SetStarterSubscriptionID sets the "starter_subscription_id" field.
func (u *UserActivationJourneyUpsert) SetStarterSubscriptionID(v int64) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldStarterSubscriptionID, v)
	return u
}

// UpdateStarterSubscriptionID sets the "starter_subscription_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateStarterSubscriptionID() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldStarterSubscriptionID)
	return u
}

// ClearStarterSubscriptionID clears the value of the "starter_subscription_id" field.
func (u *UserActivationJourneyUpsert) ClearStarterSubscriptionID() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldStarterSubscriptionID)
	return u
}

// SetStarterGrantedAt sets the "starter_granted_at" field.
func (u *UserActivationJourneyUpsert) SetStarterGrantedAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldStarterGrantedAt, v)
	return u
}

// UpdateStarterGrantedAt sets the "starter_granted_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateStarterGrantedAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldStarterGrantedAt)
	return u
}

// ClearStarterGrantedAt clears the value of the "starter_granted_at" field.
func (u *UserActivationJourneyUpsert) ClearStarterGrantedAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldStarterGrantedAt)
	return u
}

// SetStarterExpiresAt sets the "starter_expires_at" field.
func (u *UserActivationJourneyUpsert) SetStarterExpiresAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldStarterExpiresAt, v)
	return u
}

// UpdateStarterExpiresAt sets the "starter_expires_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateStarterExpiresAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldStarterExpiresAt)
	return u
}

// ClearStarterExpiresAt clears the value of the "starter_expires_at" field.
func (u *UserActivationJourneyUpsert) ClearStarterExpiresAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldStarterExpiresAt)
	return u
}

// SetRecallState sets the "recall_state" field.
func (u *UserActivationJourneyUpsert) SetRecallState(v useractivationjourney.RecallState) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldRecallState, v)
	return u
}

// UpdateRecallState sets the "recall_state" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateRecallState() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldRecallState)
	return u
}

// SetRecallSubscriptionID sets the "recall_subscription_id" field.
func (u *UserActivationJourneyUpsert) SetRecallSubscriptionID(v int64) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldRecallSubscriptionID, v)
	return u
}

// UpdateRecallSubscriptionID sets the "recall_subscription_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateRecallSubscriptionID() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldRecallSubscriptionID)
	return u
}

// ClearRecallSubscriptionID clears the value of the "recall_subscription_id" field.
func (u *UserActivationJourneyUpsert) ClearRecallSubscriptionID() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldRecallSubscriptionID)
	return u
}

// SetRecallClaimedAt sets the "recall_claimed_at" field.
func (u *UserActivationJourneyUpsert) SetRecallClaimedAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldRecallClaimedAt, v)
	return u
}

// UpdateRecallClaimedAt sets the "recall_claimed_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateRecallClaimedAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldRecallClaimedAt)
	return u
}

// ClearRecallClaimedAt clears the value of the "recall_claimed_at" field.
func (u *UserActivationJourneyUpsert) ClearRecallClaimedAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldRecallClaimedAt)
	return u
}

// SetRecallExpiresAt sets the "recall_expires_at" field.
func (u *UserActivationJourneyUpsert) SetRecallExpiresAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldRecallExpiresAt, v)
	return u
}

// UpdateRecallExpiresAt sets the "recall_expires_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateRecallExpiresAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldRecallExpiresAt)
	return u
}

// ClearRecallExpiresAt clears the value of the "recall_expires_at" field.
func (u *UserActivationJourneyUpsert) ClearRecallExpiresAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldRecallExpiresAt)
	return u
}

// SetFirstSuccessAt sets the "first_success_at" field.
func (u *UserActivationJourneyUpsert) SetFirstSuccessAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldFirstSuccessAt, v)
	return u
}

// UpdateFirstSuccessAt sets the "first_success_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateFirstSuccessAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldFirstSuccessAt)
	return u
}

// ClearFirstSuccessAt clears the value of the "first_success_at" field.
func (u *UserActivationJourneyUpsert) ClearFirstSuccessAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldFirstSuccessAt)
	return u
}

// SetNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field.
func (u *UserActivationJourneyUpsert) SetNoAttemptEmailSentAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldNoAttemptEmailSentAt, v)
	return u
}

// UpdateNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateNoAttemptEmailSentAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldNoAttemptEmailSentAt)
	return u
}

// ClearNoAttemptEmailSentAt clears the value of the "no_attempt_email_sent_at" field.
func (u *UserActivationJourneyUpsert) ClearNoAttemptEmailSentAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldNoAttemptEmailSentAt)
	return u
}

// SetAttemptedEmailSentAt sets the "attempted_email_sent_at" field.
func (u *UserActivationJourneyUpsert) SetAttemptedEmailSentAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldAttemptedEmailSentAt, v)
	return u
}

// UpdateAttemptedEmailSentAt sets the "attempted_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateAttemptedEmailSentAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldAttemptedEmailSentAt)
	return u
}

// ClearAttemptedEmailSentAt clears the value of the "attempted_email_sent_at" field.
func (u *UserActivationJourneyUpsert) ClearAttemptedEmailSentAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldAttemptedEmailSentAt)
	return u
}

// SetPaidSupportEmailSentAt sets the "paid_support_email_sent_at" field.
func (u *UserActivationJourneyUpsert) SetPaidSupportEmailSentAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldPaidSupportEmailSentAt, v)
	return u
}

// UpdatePaidSupportEmailSentAt sets the "paid_support_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdatePaidSupportEmailSentAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldPaidSupportEmailSentAt)
	return u
}

// ClearPaidSupportEmailSentAt clears the value of the "paid_support_email_sent_at" field.
func (u *UserActivationJourneyUpsert) ClearPaidSupportEmailSentAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldPaidSupportEmailSentAt)
	return u
}

// SetRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field.
func (u *UserActivationJourneyUpsert) SetRecallAvailableEmailSentAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldRecallAvailableEmailSentAt, v)
	return u
}

// UpdateRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateRecallAvailableEmailSentAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldRecallAvailableEmailSentAt)
	return u
}

// ClearRecallAvailableEmailSentAt clears the value of the "recall_available_email_sent_at" field.
func (u *UserActivationJourneyUpsert) ClearRecallAvailableEmailSentAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldRecallAvailableEmailSentAt)
	return u
}

// SetRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field.
func (u *UserActivationJourneyUpsert) SetRecallExpiredEmailSentAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldRecallExpiredEmailSentAt, v)
	return u
}

// UpdateRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateRecallExpiredEmailSentAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldRecallExpiredEmailSentAt)
	return u
}

// ClearRecallExpiredEmailSentAt clears the value of the "recall_expired_email_sent_at" field.
func (u *UserActivationJourneyUpsert) ClearRecallExpiredEmailSentAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldRecallExpiredEmailSentAt)
	return u
}

// SetLastEmailSentAt sets the "last_email_sent_at" field.
func (u *UserActivationJourneyUpsert) SetLastEmailSentAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldLastEmailSentAt, v)
	return u
}

// UpdateLastEmailSentAt sets the "last_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateLastEmailSentAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldLastEmailSentAt)
	return u
}

// ClearLastEmailSentAt clears the value of the "last_email_sent_at" field.
func (u *UserActivationJourneyUpsert) ClearLastEmailSentAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldLastEmailSentAt)
	return u
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (u *UserActivationJourneyUpsert) SetLastEvaluatedAt(v time.Time) *UserActivationJourneyUpsert {
	u.Set(useractivationjourney.FieldLastEvaluatedAt, v)
	return u
}

// UpdateLastEvaluatedAt sets the "last_evaluated_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsert) UpdateLastEvaluatedAt() *UserActivationJourneyUpsert {
	u.SetExcluded(useractivationjourney.FieldLastEvaluatedAt)
	return u
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (u *UserActivationJourneyUpsert) ClearLastEvaluatedAt() *UserActivationJourneyUpsert {
	u.SetNull(useractivationjourney.FieldLastEvaluatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserActivationJourney.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserActivationJourneyUpsertOne) UpdateNewValues() *UserActivationJourneyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(useractivationjourney.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserActivationJourney.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserActivationJourneyUpsertOne) Ignore() *UserActivationJourneyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserActivationJourneyUpsertOne) DoNothing() *UserActivationJourneyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserActivationJourneyCreate.OnConflict
// documentation for more info.
func (u *UserActivationJourneyUpsertOne) Update(set func(*UserActivationJourneyUpsert)) *UserActivationJourneyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserActivationJourneyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserActivationJourneyUpsertOne) SetUpdatedAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateUpdatedAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserActivationJourneyUpsertOne) SetUserID(v int64) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateUserID() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateUserID()
	})
}

// SetCampaignSource sets the "campaign_source" field.
func (u *UserActivationJourneyUpsertOne) SetCampaignSource(v string) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetCampaignSource(v)
	})
}

// UpdateCampaignSource sets the "campaign_source" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateCampaignSource() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateCampaignSource()
	})
}

// SetStarterState sets the "starter_state" field.
func (u *UserActivationJourneyUpsertOne) SetStarterState(v useractivationjourney.StarterState) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetStarterState(v)
	})
}

// UpdateStarterState sets the "starter_state" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateStarterState() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateStarterState()
	})
}

// SetStarterSubscriptionID sets the "starter_subscription_id" field.
func (u *UserActivationJourneyUpsertOne) SetStarterSubscriptionID(v int64) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetStarterSubscriptionID(v)
	})
}

// UpdateStarterSubscriptionID sets the "starter_subscription_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateStarterSubscriptionID() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateStarterSubscriptionID()
	})
}

// ClearStarterSubscriptionID clears the value of the "starter_subscription_id" field.
func (u *UserActivationJourneyUpsertOne) ClearStarterSubscriptionID() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearStarterSubscriptionID()
	})
}

// SetStarterGrantedAt sets the "starter_granted_at" field.
func (u *UserActivationJourneyUpsertOne) SetStarterGrantedAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetStarterGrantedAt(v)
	})
}

// UpdateStarterGrantedAt sets the "starter_granted_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateStarterGrantedAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateStarterGrantedAt()
	})
}

// ClearStarterGrantedAt clears the value of the "starter_granted_at" field.
func (u *UserActivationJourneyUpsertOne) ClearStarterGrantedAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearStarterGrantedAt()
	})
}

// SetStarterExpiresAt sets the "starter_expires_at" field.
func (u *UserActivationJourneyUpsertOne) SetStarterExpiresAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetStarterExpiresAt(v)
	})
}

// UpdateStarterExpiresAt sets the "starter_expires_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateStarterExpiresAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateStarterExpiresAt()
	})
}

// ClearStarterExpiresAt clears the value of the "starter_expires_at" field.
func (u *UserActivationJourneyUpsertOne) ClearStarterExpiresAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearStarterExpiresAt()
	})
}

// SetRecallState sets the "recall_state" field.
func (u *UserActivationJourneyUpsertOne) SetRecallState(v useractivationjourney.RecallState) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallState(v)
	})
}

// UpdateRecallState sets the "recall_state" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateRecallState() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallState()
	})
}

// SetRecallSubscriptionID sets the "recall_subscription_id" field.
func (u *UserActivationJourneyUpsertOne) SetRecallSubscriptionID(v int64) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallSubscriptionID(v)
	})
}

// UpdateRecallSubscriptionID sets the "recall_subscription_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateRecallSubscriptionID() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallSubscriptionID()
	})
}

// ClearRecallSubscriptionID clears the value of the "recall_subscription_id" field.
func (u *UserActivationJourneyUpsertOne) ClearRecallSubscriptionID() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallSubscriptionID()
	})
}

// SetRecallClaimedAt sets the "recall_claimed_at" field.
func (u *UserActivationJourneyUpsertOne) SetRecallClaimedAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallClaimedAt(v)
	})
}

// UpdateRecallClaimedAt sets the "recall_claimed_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateRecallClaimedAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallClaimedAt()
	})
}

// ClearRecallClaimedAt clears the value of the "recall_claimed_at" field.
func (u *UserActivationJourneyUpsertOne) ClearRecallClaimedAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallClaimedAt()
	})
}

// SetRecallExpiresAt sets the "recall_expires_at" field.
func (u *UserActivationJourneyUpsertOne) SetRecallExpiresAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallExpiresAt(v)
	})
}

// UpdateRecallExpiresAt sets the "recall_expires_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateRecallExpiresAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallExpiresAt()
	})
}

// ClearRecallExpiresAt clears the value of the "recall_expires_at" field.
func (u *UserActivationJourneyUpsertOne) ClearRecallExpiresAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallExpiresAt()
	})
}

// SetFirstSuccessAt sets the "first_success_at" field.
func (u *UserActivationJourneyUpsertOne) SetFirstSuccessAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetFirstSuccessAt(v)
	})
}

// UpdateFirstSuccessAt sets the "first_success_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateFirstSuccessAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateFirstSuccessAt()
	})
}

// ClearFirstSuccessAt clears the value of the "first_success_at" field.
func (u *UserActivationJourneyUpsertOne) ClearFirstSuccessAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearFirstSuccessAt()
	})
}

// SetNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) SetNoAttemptEmailSentAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetNoAttemptEmailSentAt(v)
	})
}

// UpdateNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateNoAttemptEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateNoAttemptEmailSentAt()
	})
}

// ClearNoAttemptEmailSentAt clears the value of the "no_attempt_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) ClearNoAttemptEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearNoAttemptEmailSentAt()
	})
}

// SetAttemptedEmailSentAt sets the "attempted_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) SetAttemptedEmailSentAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetAttemptedEmailSentAt(v)
	})
}

// UpdateAttemptedEmailSentAt sets the "attempted_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateAttemptedEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateAttemptedEmailSentAt()
	})
}

// ClearAttemptedEmailSentAt clears the value of the "attempted_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) ClearAttemptedEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearAttemptedEmailSentAt()
	})
}

// SetPaidSupportEmailSentAt sets the "paid_support_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) SetPaidSupportEmailSentAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetPaidSupportEmailSentAt(v)
	})
}

// UpdatePaidSupportEmailSentAt sets the "paid_support_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdatePaidSupportEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdatePaidSupportEmailSentAt()
	})
}

// ClearPaidSupportEmailSentAt clears the value of the "paid_support_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) ClearPaidSupportEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearPaidSupportEmailSentAt()
	})
}

// SetRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) SetRecallAvailableEmailSentAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallAvailableEmailSentAt(v)
	})
}

// UpdateRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateRecallAvailableEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallAvailableEmailSentAt()
	})
}

// ClearRecallAvailableEmailSentAt clears the value of the "recall_available_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) ClearRecallAvailableEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallAvailableEmailSentAt()
	})
}

// SetRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) SetRecallExpiredEmailSentAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallExpiredEmailSentAt(v)
	})
}

// UpdateRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateRecallExpiredEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallExpiredEmailSentAt()
	})
}

// ClearRecallExpiredEmailSentAt clears the value of the "recall_expired_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) ClearRecallExpiredEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallExpiredEmailSentAt()
	})
}

// SetLastEmailSentAt sets the "last_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) SetLastEmailSentAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetLastEmailSentAt(v)
	})
}

// UpdateLastEmailSentAt sets the "last_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateLastEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateLastEmailSentAt()
	})
}

// ClearLastEmailSentAt clears the value of the "last_email_sent_at" field.
func (u *UserActivationJourneyUpsertOne) ClearLastEmailSentAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearLastEmailSentAt()
	})
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (u *UserActivationJourneyUpsertOne) SetLastEvaluatedAt(v time.Time) *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetLastEvaluatedAt(v)
	})
}

// UpdateLastEvaluatedAt sets the "last_evaluated_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertOne) UpdateLastEvaluatedAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateLastEvaluatedAt()
	})
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (u *UserActivationJourneyUpsertOne) ClearLastEvaluatedAt() *UserActivationJourneyUpsertOne {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearLastEvaluatedAt()
	})
}

// Exec executes the query.
func (u *UserActivationJourneyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserActivationJourneyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserActivationJourneyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserActivationJourneyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserActivationJourneyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserActivationJourneyCreateBulk is the builder for creating many UserActivationJourney entities in bulk.
type UserActivationJourneyCreateBulk struct {
	config
	err      error
	builders []*UserActivationJourneyCreate
	conflict []sql.ConflictOption
}

// Save creates the UserActivationJourney entities in the database.
func (_c *UserActivationJourneyCreateBulk) Save(ctx context.Context) ([]*UserActivationJourney, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserActivationJourney, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserActivationJourneyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserActivationJourneyCreateBulk) SaveX(ctx context.Context) []*UserActivationJourney {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserActivationJourneyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserActivationJourneyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserActivationJourney.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserActivationJourneyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserActivationJourneyCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserActivationJourneyUpsertBulk {
	_c.conflict = opts
	return &UserActivationJourneyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserActivationJourney.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserActivationJourneyCreateBulk) OnConflictColumns(columns ...string) *UserActivationJourneyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserActivationJourneyUpsertBulk{
		create: _c,
	}
}

// UserActivationJourneyUpsertBulk is the builder for "upsert"-ing
// a bulk of UserActivationJourney nodes.
type UserActivationJourneyUpsertBulk struct {
	create *UserActivationJourneyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserActivationJourney.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserActivationJourneyUpsertBulk) UpdateNewValues() *UserActivationJourneyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(useractivationjourney.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserActivationJourney.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserActivationJourneyUpsertBulk) Ignore() *UserActivationJourneyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserActivationJourneyUpsertBulk) DoNothing() *UserActivationJourneyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserActivationJourneyCreateBulk.OnConflict
// documentation for more info.
func (u *UserActivationJourneyUpsertBulk) Update(set func(*UserActivationJourneyUpsert)) *UserActivationJourneyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserActivationJourneyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserActivationJourneyUpsertBulk) SetUpdatedAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateUpdatedAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserActivationJourneyUpsertBulk) SetUserID(v int64) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateUserID() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateUserID()
	})
}

// SetCampaignSource sets the "campaign_source" field.
func (u *UserActivationJourneyUpsertBulk) SetCampaignSource(v string) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetCampaignSource(v)
	})
}

// UpdateCampaignSource sets the "campaign_source" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateCampaignSource() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateCampaignSource()
	})
}

// SetStarterState sets the "starter_state" field.
func (u *UserActivationJourneyUpsertBulk) SetStarterState(v useractivationjourney.StarterState) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetStarterState(v)
	})
}

// UpdateStarterState sets the "starter_state" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateStarterState() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateStarterState()
	})
}

// SetStarterSubscriptionID sets the "starter_subscription_id" field.
func (u *UserActivationJourneyUpsertBulk) SetStarterSubscriptionID(v int64) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetStarterSubscriptionID(v)
	})
}

// UpdateStarterSubscriptionID sets the "starter_subscription_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateStarterSubscriptionID() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateStarterSubscriptionID()
	})
}

// ClearStarterSubscriptionID clears the value of the "starter_subscription_id" field.
func (u *UserActivationJourneyUpsertBulk) ClearStarterSubscriptionID() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearStarterSubscriptionID()
	})
}

// SetStarterGrantedAt sets the "starter_granted_at" field.
func (u *UserActivationJourneyUpsertBulk) SetStarterGrantedAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetStarterGrantedAt(v)
	})
}

// UpdateStarterGrantedAt sets the "starter_granted_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateStarterGrantedAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateStarterGrantedAt()
	})
}

// ClearStarterGrantedAt clears the value of the "starter_granted_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearStarterGrantedAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearStarterGrantedAt()
	})
}

// SetStarterExpiresAt sets the "starter_expires_at" field.
func (u *UserActivationJourneyUpsertBulk) SetStarterExpiresAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetStarterExpiresAt(v)
	})
}

// UpdateStarterExpiresAt sets the "starter_expires_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateStarterExpiresAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateStarterExpiresAt()
	})
}

// ClearStarterExpiresAt clears the value of the "starter_expires_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearStarterExpiresAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearStarterExpiresAt()
	})
}

// SetRecallState sets the "recall_state" field.
func (u *UserActivationJourneyUpsertBulk) SetRecallState(v useractivationjourney.RecallState) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallState(v)
	})
}

// UpdateRecallState sets the "recall_state" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateRecallState() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallState()
	})
}

// SetRecallSubscriptionID sets the "recall_subscription_id" field.
func (u *UserActivationJourneyUpsertBulk) SetRecallSubscriptionID(v int64) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallSubscriptionID(v)
	})
}

// UpdateRecallSubscriptionID sets the "recall_subscription_id" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateRecallSubscriptionID() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallSubscriptionID()
	})
}

// ClearRecallSubscriptionID clears the value of the "recall_subscription_id" field.
func (u *UserActivationJourneyUpsertBulk) ClearRecallSubscriptionID() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallSubscriptionID()
	})
}

// SetRecallClaimedAt sets the "recall_claimed_at" field.
func (u *UserActivationJourneyUpsertBulk) SetRecallClaimedAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallClaimedAt(v)
	})
}

// UpdateRecallClaimedAt sets the "recall_claimed_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateRecallClaimedAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallClaimedAt()
	})
}

// ClearRecallClaimedAt clears the value of the "recall_claimed_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearRecallClaimedAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallClaimedAt()
	})
}

// SetRecallExpiresAt sets the "recall_expires_at" field.
func (u *UserActivationJourneyUpsertBulk) SetRecallExpiresAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallExpiresAt(v)
	})
}

// UpdateRecallExpiresAt sets the "recall_expires_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateRecallExpiresAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallExpiresAt()
	})
}

// ClearRecallExpiresAt clears the value of the "recall_expires_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearRecallExpiresAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallExpiresAt()
	})
}

// SetFirstSuccessAt sets the "first_success_at" field.
func (u *UserActivationJourneyUpsertBulk) SetFirstSuccessAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetFirstSuccessAt(v)
	})
}

// UpdateFirstSuccessAt sets the "first_success_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateFirstSuccessAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateFirstSuccessAt()
	})
}

// ClearFirstSuccessAt clears the value of the "first_success_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearFirstSuccessAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearFirstSuccessAt()
	})
}

// SetNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) SetNoAttemptEmailSentAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetNoAttemptEmailSentAt(v)
	})
}

// UpdateNoAttemptEmailSentAt sets the "no_attempt_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateNoAttemptEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateNoAttemptEmailSentAt()
	})
}

// ClearNoAttemptEmailSentAt clears the value of the "no_attempt_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearNoAttemptEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearNoAttemptEmailSentAt()
	})
}

// SetAttemptedEmailSentAt sets the "attempted_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) SetAttemptedEmailSentAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetAttemptedEmailSentAt(v)
	})
}

// UpdateAttemptedEmailSentAt sets the "attempted_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateAttemptedEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateAttemptedEmailSentAt()
	})
}

// ClearAttemptedEmailSentAt clears the value of the "attempted_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearAttemptedEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearAttemptedEmailSentAt()
	})
}

// SetPaidSupportEmailSentAt sets the "paid_support_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) SetPaidSupportEmailSentAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetPaidSupportEmailSentAt(v)
	})
}

// UpdatePaidSupportEmailSentAt sets the "paid_support_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdatePaidSupportEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdatePaidSupportEmailSentAt()
	})
}

// ClearPaidSupportEmailSentAt clears the value of the "paid_support_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearPaidSupportEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearPaidSupportEmailSentAt()
	})
}

// SetRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) SetRecallAvailableEmailSentAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallAvailableEmailSentAt(v)
	})
}

// UpdateRecallAvailableEmailSentAt sets the "recall_available_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateRecallAvailableEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallAvailableEmailSentAt()
	})
}

// ClearRecallAvailableEmailSentAt clears the value of the "recall_available_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearRecallAvailableEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallAvailableEmailSentAt()
	})
}

// SetRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) SetRecallExpiredEmailSentAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetRecallExpiredEmailSentAt(v)
	})
}

// UpdateRecallExpiredEmailSentAt sets the "recall_expired_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateRecallExpiredEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateRecallExpiredEmailSentAt()
	})
}

// ClearRecallExpiredEmailSentAt clears the value of the "recall_expired_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearRecallExpiredEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearRecallExpiredEmailSentAt()
	})
}

// SetLastEmailSentAt sets the "last_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) SetLastEmailSentAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetLastEmailSentAt(v)
	})
}

// UpdateLastEmailSentAt sets the "last_email_sent_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateLastEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateLastEmailSentAt()
	})
}

// ClearLastEmailSentAt clears the value of the "last_email_sent_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearLastEmailSentAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearLastEmailSentAt()
	})
}

// SetLastEvaluatedAt sets the "last_evaluated_at" field.
func (u *UserActivationJourneyUpsertBulk) SetLastEvaluatedAt(v time.Time) *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.SetLastEvaluatedAt(v)
	})
}

// UpdateLastEvaluatedAt sets the "last_evaluated_at" field to the value that was provided on create.
func (u *UserActivationJourneyUpsertBulk) UpdateLastEvaluatedAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.UpdateLastEvaluatedAt()
	})
}

// ClearLastEvaluatedAt clears the value of the "last_evaluated_at" field.
func (u *UserActivationJourneyUpsertBulk) ClearLastEvaluatedAt() *UserActivationJourneyUpsertBulk {
	return u.Update(func(s *UserActivationJourneyUpsert) {
		s.ClearLastEvaluatedAt()
	})
}

// Exec executes the query.
func (u *UserActivationJourneyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserActivationJourneyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserActivationJourneyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserActivationJourneyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
