// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/useractivationjourney"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UserActivationJourney is the model entity for the UserActivationJourney schema.
type UserActivationJourney struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CampaignSource holds the value of the "campaign_source" field.
	CampaignSource string `json:"campaign_source,omitempty"`
	// Observable starter lifecycle state; eligibility must be re-evaluated from current evidence.
	StarterState useractivationjourney.StarterState `json:"starter_state,omitempty"`
	// StarterSubscriptionID holds the value of the "starter_subscription_id" field.
	StarterSubscriptionID *int64 `json:"starter_subscription_id,omitempty"`
	// StarterGrantedAt holds the value of the "starter_granted_at" field.
	StarterGrantedAt *time.Time `json:"starter_granted_at,omitempty"`
	// StarterExpiresAt holds the value of the "starter_expires_at" field.
	StarterExpiresAt *time.Time `json:"starter_expires_at,omitempty"`
	// Observable recall lifecycle state; eligibility must be re-evaluated from current evidence.
	RecallState useractivationjourney.RecallState `json:"recall_state,omitempty"`
	// RecallSubscriptionID holds the value of the "recall_subscription_id" field.
	RecallSubscriptionID *int64 `json:"recall_subscription_id,omitempty"`
	// RecallClaimedAt holds the value of the "recall_claimed_at" field.
	RecallClaimedAt *time.Time `json:"recall_claimed_at,omitempty"`
	// RecallExpiresAt holds the value of the "recall_expires_at" field.
	RecallExpiresAt *time.Time `json:"recall_expires_at,omitempty"`
	// FirstSuccessAt holds the value of the "first_success_at" field.
	FirstSuccessAt *time.Time `json:"first_success_at,omitempty"`
	// NoAttemptEmailSentAt holds the value of the "no_attempt_email_sent_at" field.
	NoAttemptEmailSentAt *time.Time `json:"no_attempt_email_sent_at,omitempty"`
	// AttemptedEmailSentAt holds the value of the "attempted_email_sent_at" field.
	AttemptedEmailSentAt *time.Time `json:"attempted_email_sent_at,omitempty"`
	// PaidSupportEmailSentAt holds the value of the "paid_support_email_sent_at" field.
	PaidSupportEmailSentAt *time.Time `json:"paid_support_email_sent_at,omitempty"`
	// RecallAvailableEmailSentAt holds the value of the "recall_available_email_sent_at" field.
	RecallAvailableEmailSentAt *time.Time `json:"recall_available_email_sent_at,omitempty"`
	// RecallExpiredEmailSentAt holds the value of the "recall_expired_email_sent_at" field.
	RecallExpiredEmailSentAt *time.Time `json:"recall_expired_email_sent_at,omitempty"`
	// LastEmailSentAt holds the value of the "last_email_sent_at" field.
	LastEmailSentAt *time.Time `json:"last_email_sent_at,omitempty"`
	// LastEvaluatedAt holds the value of the "last_evaluated_at" field.
	LastEvaluatedAt *time.Time `json:"last_evaluated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserActivationJourneyQuery when eager-loading is set.
	Edges        UserActivationJourneyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserActivationJourneyEdges holds the relations/edges for other nodes in the graph.
type UserActivationJourneyEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// StarterSubscription holds the value of the starter_subscription edge.
	StarterSubscription *UserSubscription `json:"starter_subscription,omitempty"`
	// RecallSubscription holds the value of the recall_subscription edge.
	RecallSubscription *UserSubscription `json:"recall_subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserActivationJourneyEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// StarterSubscriptionOrErr returns the StarterSubscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserActivationJourneyEdges) StarterSubscriptionOrErr() (*UserSubscription, error) {
	if e.StarterSubscription != nil {
		return e.StarterSubscription, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "starter_subscription"}
}

// RecallSubscriptionOrErr returns the RecallSubscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserActivationJourneyEdges) RecallSubscriptionOrErr() (*UserSubscription, error) {
	if e.RecallSubscription != nil {
		return e.RecallSubscription, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "recall_subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserActivationJourney) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case useractivationjourney.FieldID, useractivationjourney.FieldUserID, useractivationjourney.FieldStarterSubscriptionID, useractivationjourney.FieldRecallSubscriptionID:
			values[i] = new(sql.NullInt64)
		case useractivationjourney.FieldCampaignSource, useractivationjourney.FieldStarterState, useractivationjourney.FieldRecallState:
			values[i] = new(sql.NullString)
		case useractivationjourney.FieldCreatedAt, useractivationjourney.FieldUpdatedAt, useractivationjourney.FieldStarterGrantedAt, useractivationjourney.FieldStarterExpiresAt, useractivationjourney.FieldRecallClaimedAt, useractivationjourney.FieldRecallExpiresAt, useractivationjourney.FieldFirstSuccessAt, useractivationjourney.FieldNoAttemptEmailSentAt, useractivationjourney.FieldAttemptedEmailSentAt, useractivationjourney.FieldPaidSupportEmailSentAt, useractivationjourney.FieldRecallAvailableEmailSentAt, useractivationjourney.FieldRecallExpiredEmailSentAt, useractivationjourney.FieldLastEmailSentAt, useractivationjourney.FieldLastEvaluatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserActivationJourney fields.
func (_m *UserActivationJourney) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case useractivationjourney.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case useractivationjourney.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case useractivationjourney.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case useractivationjourney.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case useractivationjourney.FieldCampaignSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field campaign_source", values[i])
			} else if value.Valid {
				_m.CampaignSource = value.String
			}
		case useractivationjourney.FieldStarterState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field starter_state", values[i])
			} else if value.Valid {
				_m.StarterState = useractivationjourney.StarterState(value.String)
			}
		case useractivationjourney.FieldStarterSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field starter_subscription_id", values[i])
			} else if value.Valid {
				_m.StarterSubscriptionID = new(int64)
				*_m.StarterSubscriptionID = value.Int64
			}
		case useractivationjourney.FieldStarterGrantedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starter_granted_at", values[i])
			} else if value.Valid {
				_m.StarterGrantedAt = new(time.Time)
				*_m.StarterGrantedAt = value.Time
			}
		case useractivationjourney.FieldStarterExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starter_expires_at", values[i])
			} else if value.Valid {
				_m.StarterExpiresAt = new(time.Time)
				*_m.StarterExpiresAt = value.Time
			}
		case useractivationjourney.FieldRecallState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recall_state", values[i])
			} else if value.Valid {
				_m.RecallState = useractivationjourney.RecallState(value.String)
			}
		case useractivationjourney.FieldRecallSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recall_subscription_id", values[i])
			} else if value.Valid {
				_m.RecallSubscriptionID = new(int64)
				*_m.RecallSubscriptionID = value.Int64
			}
		case useractivationjourney.FieldRecallClaimedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recall_claimed_at", values[i])
			} else if value.Valid {
				_m.RecallClaimedAt = new(time.Time)
				*_m.RecallClaimedAt = value.Time
			}
		case useractivationjourney.FieldRecallExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recall_expires_at", values[i])
			} else if value.Valid {
				_m.RecallExpiresAt = new(time.Time)
				*_m.RecallExpiresAt = value.Time
			}
		case useractivationjourney.FieldFirstSuccessAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_success_at", values[i])
			} else if value.Valid {
				_m.FirstSuccessAt = new(time.Time)
				*_m.FirstSuccessAt = value.Time
			}
		case useractivationjourney.FieldNoAttemptEmailSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field no_attempt_email_sent_at", values[i])
			} else if value.Valid {
				_m.NoAttemptEmailSentAt = new(time.Time)
				*_m.NoAttemptEmailSentAt = value.Time
			}
		case useractivationjourney.FieldAttemptedEmailSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field attempted_email_sent_at", values[i])
			} else if value.Valid {
				_m.AttemptedEmailSentAt = new(time.Time)
				*_m.AttemptedEmailSentAt = value.Time
			}
		case useractivationjourney.FieldPaidSupportEmailSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_support_email_sent_at", values[i])
			} else if value.Valid {
				_m.PaidSupportEmailSentAt = new(time.Time)
				*_m.PaidSupportEmailSentAt = value.Time
			}
		case useractivationjourney.FieldRecallAvailableEmailSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recall_available_email_sent_at", values[i])
			} else if value.Valid {
				_m.RecallAvailableEmailSentAt = new(time.Time)
				*_m.RecallAvailableEmailSentAt = value.Time
			}
		case useractivationjourney.FieldRecallExpiredEmailSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recall_expired_email_sent_at", values[i])
			} else if value.Valid {
				_m.RecallExpiredEmailSentAt = new(time.Time)
				*_m.RecallExpiredEmailSentAt = value.Time
			}
		case useractivationjourney.FieldLastEmailSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_email_sent_at", values[i])
			} else if value.Valid {
				_m.LastEmailSentAt = new(time.Time)
				*_m.LastEmailSentAt = value.Time
			}
		case useractivationjourney.FieldLastEvaluatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_evaluated_at", values[i])
			} else if value.Valid {
				_m.LastEvaluatedAt = new(time.Time)
				*_m.LastEvaluatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserActivationJourney.
// This includes values selected through modifiers, order, etc.
func (_m *UserActivationJourney) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserActivationJourney entity.
func (_m *UserActivationJourney) QueryUser() *UserQuery {
	return NewUserActivationJourneyClient(_m.config).QueryUser(_m)
}

// QueryStarterSubscription queries the "starter_subscription" edge of the UserActivationJourney entity.
func (_m *UserActivationJourney) QueryStarterSubscription() *UserSubscriptionQuery {
	return NewUserActivationJourneyClient(_m.config).QueryStarterSubscription(_m)
}

// QueryRecallSubscription queries the "recall_subscription" edge of the UserActivationJourney entity.
func (_m *UserActivationJourney) QueryRecallSubscription() *UserSubscriptionQuery {
	return NewUserActivationJourneyClient(_m.config).QueryRecallSubscription(_m)
}

// Update returns a builder for updating this UserActivationJourney.
// Note that you need to call UserActivationJourney.Unwrap() before calling this method if this UserActivationJourney
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserActivationJourney) Update() *UserActivationJourneyUpdateOne {
	return NewUserActivationJourneyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserActivationJourney entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserActivationJourney) Unwrap() *UserActivationJourney {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserActivationJourney is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserActivationJourney) String() string {
	var builder strings.Builder
	builder.WriteString("UserActivationJourney(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("campaign_source=")
	builder.WriteString(_m.CampaignSource)
	builder.WriteString(", ")
	builder.WriteString("starter_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.StarterState))
	builder.WriteString(", ")
	if v := _m.StarterSubscriptionID; v != nil {
		builder.WriteString("starter_subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StarterGrantedAt; v != nil {
		builder.WriteString("starter_granted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.StarterExpiresAt; v != nil {
		builder.WriteString("starter_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("recall_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecallState))
	builder.WriteString(", ")
	if v := _m.RecallSubscriptionID; v != nil {
		builder.WriteString("recall_subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RecallClaimedAt; v != nil {
		builder.WriteString("recall_claimed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RecallExpiresAt; v != nil {
		builder.WriteString("recall_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FirstSuccessAt; v != nil {
		builder.WriteString("first_success_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NoAttemptEmailSentAt; v != nil {
		builder.WriteString("no_attempt_email_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AttemptedEmailSentAt; v != nil {
		builder.WriteString("attempted_email_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PaidSupportEmailSentAt; v != nil {
		builder.WriteString("paid_support_email_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RecallAvailableEmailSentAt; v != nil {
		builder.WriteString("recall_available_email_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RecallExpiredEmailSentAt; v != nil {
		builder.WriteString("recall_expired_email_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastEmailSentAt; v != nil {
		builder.WriteString("last_email_sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastEvaluatedAt; v != nil {
		builder.WriteString("last_evaluated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UserActivationJourneys is a parsable slice of UserActivationJourney.
type UserActivationJourneys []*UserActivationJourney
